---
sidebar: sidebar 
permalink: rn_whatsnew_vcp.html 
summary: 瞭解NetApp Element 此版本的vCenter Server適用的更新功能。 
keywords: netapp, vcp, vcenter, plugin, element, new, whats new 
---
= vCenter Server的更新功能NetApp Element
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:keywords: netapp, vcp, vcenter, plugin, element, new, whats new


[role="lead"]
vCenter Server 4.8版的更新程式包含安全性改善、記憶體使用率改善、以及協力廠商程式庫升級。NetApp Element

vCenter Server 4.8版的支援VMware vCenter Server 4.8外掛程式可與2.19版的管理服務搭配使用。NetApp Element



== vCenter Server 4.7的版插件NetApp Element

vCenter Server 4.7版的支援程式包含重要的安全性改良功能、可進一步開發在中所做的改善NetApp Element https://security.netapp.com/advisory/ntap-20210315-0001/["最新的管理服務2.17.56修補程式"] 版本：

在4.7版中、外掛程式現在支援vSphere 7.0 Update 2的元件、包括vCenter Server、ESXi和vSphere HTML5 Web Client。

vCenter Server 4.7版的VMware vCenter Server隨附於2.18版管理服務中。NetApp Element



== vCenter Server 4.6的VMware vCenter外掛程式NetApp Element

有了4.6版、外掛程式現在可支援vSphere 7.0 Update 1的元件、包括vCenter Server、ESXi和vSphere HTML5 Web Client。

vCenter Server 4.6版的VMware vCenter Server 4.6外掛程式可與2.16版管理服務搭配使用。NetApp Element

[discrete]
== 如需詳細資訊、請參閱

* link:reference_earlier_versions.html["舊版NetApp Element 的不整合外掛程式文件"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["混合雲控制與管理服務版本說明KB"^]
* https://docs.netapp.com/us-en/hci/index.html["資訊文件NetApp HCI"^]
* https://www.netapp.com/data-storage/solidfire/documentation["「元件與元素資源」頁面SolidFire"^]

