---
sidebar: sidebar 
permalink: rn_whatsnew_vcp.html 
summary: 瞭解NetApp Element 此版本VMware vCenter Server適用的VMware vCenter外掛程式的新功能。 
keywords: netapp, vcp, vcenter, plugin, element, new, whats new 
---
= VMware vCenter Server的更新功能NetApp Element
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
vCenter Server 5.0版的VMware vCenter外掛程式包含遠端外掛程式架構、可將外掛程式功能整合至vSphere Client、而無需在vCenter Server內部執行。NetApp Element遠端架構支援外掛隔離、並可橫向擴充在大型vSphere環境中運作的外掛程式。遠端元素外掛程式會部署在管理節點內部的Docker容器中、以及管理服務。 link:vcp_concept_remote_plugin_architecture.html["深入瞭解。"]

Element vCenter外掛程式5.0支援VMware vSphere 8.0、7.0及7.0 Update 1、2及3、包括vCenter Server、ESXi及vSphere HTML5 Web Client。

Element vCenter外掛程式5.0隨2.22.7版的管理服務一起提供。如果您不使用外掛程式、這是選擇性升級、因為所有其他服務和功能都與2.21.61版相同。如需最新管理服務更新的資訊、請參閱 https://library.netapp.com/ecm/ecm_download_file/ECMLP2884458["管理服務版本說明2.21.61"^]。



== vCenter Server 4．10的插件NetApp Element

Element vCenter外掛程式4.10包含已解決的問題、包括安全性弱點、可能會大幅減少升級期間發生的中斷情形、並在某些環境中強化日常作業。在外掛程式的4月10日版中、線上說明連結已轉換為這項功能 link:index.html["文件連結"]。若要從外掛程式中存取線上說明連結、您必須擁有網路存取權。

Element vCenter外掛程式4．10隨附於2.21．61版的管理服務中。



== vCenter Server 4.9的插件NetApp Element

vCenter Server 4.9版的支援功能可還原vSphere 6.5的支援、包括vCenter Server、ESXi和vSphere HTML5 Web Client。NetApp Element

Element vCenter外掛程式4.9可與2.20.69版的管理服務搭配使用。



== vCenter Server 4.8的版插件NetApp Element

Element vCenter外掛程式4.8包含安全性改善、記憶體使用率改善、以及協力廠商程式庫升級。

Element vCenter外掛程式4.8隨2.19版管理服務一起提供。



== vCenter Server 4.7的版插件NetApp Element

Element vCenter外掛程式4.7包含重要的安全性改良功能、可進一步開發在中所做的改善 https://security.netapp.com/advisory/ntap-20210315-0001/["最新的管理服務2.17.56修補程式"] 版本：

在4.7版中、外掛程式現在支援vSphere 7.0 Update 2的元件、包括vCenter Server、ESXi和vSphere HTML5 Web Client。

Element vCenter外掛程式4.7隨2.18版管理服務一起提供。



== vCenter Server 4.6的VMware vCenter外掛程式NetApp Element

有了4.6版、外掛程式現在可支援vSphere 7.0 Update 1的元件、包括vCenter Server、ESXi和vSphere HTML5 Web Client。

Element vCenter外掛程式4.6可搭配2.16版的管理服務使用。



== 如需詳細資訊、請參閱

* link:reference_earlier_versions.html["舊版NetApp Element 的不整合外掛程式文件"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Management_services_for_Element_Software_and_NetApp_HCI/Management_Services_Release_Notes["混合雲控制與管理服務版本說明KB"^]
* https://docs.netapp.com/us-en/hci/index.html["資訊文件NetApp HCI"^]
* https://www.netapp.com/data-storage/solidfire/documentation["「元件與元素資源」頁面SolidFire"^]

