---
sidebar: sidebar 
permalink: vcp_task_reports_qossioc.html 
summary: 您可以在NetApp Element 適用於vCenter Server的VMware vCenter外掛程式中、檢視連線至所選叢集的iSCSI工作階段相關資訊。 
keywords: netapp, hci, vcp, vcenter, element, monitor, report, qossioc, cluster, performance 
---
= 利用QoSSIOC事件監控VM效能分層
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
當具有啟用QoS的資料存放區的VM重新設定或發出電源或來賓事件時、您可以檢視與QoSSIOC相關的事件。

您可以從NetApp Element vCenter Server的VMware vCenter外掛程式的「VMware組態」擴充點檢視QoSSIOC事件NetApp Element 。

QoSSIOC事件會從本機新增的叢集顯示。在連結模式環境中、登入已在本機新增叢集的vSphere Web Client、以檢視該叢集的QoSSIOC事件。


NOTE: 使用NetApp Element vCenter Server的VMware vCenter外掛程式、使用管理其他vCenter Server的叢集資源 link:vcp_concept_linkedmode.html["vCenter連結模式"] 僅限於本機儲存叢集。

.您需要的是 #8217 ；需要的是什麼
* 至少必須新增並執行一個叢集。
* QoSSIOC服務必須使用外掛程式的QoSSIOC設定頁面進行設定和驗證執行。
* 至少一個資料存放區必須啟用QoSSIOC自動化。


.步驟
. 從vCenter外掛程式中選取* NetApp Element 《組態*》。
. 選擇* QoSSIOC事件*。




== QoSSIOC事件資料

* *日期*：QoSSIOC活動的日期與時間。
* *資料存放區名稱*：使用者定義的資料存放區名稱。
* *叢集IP*：包含事件來源資料存放區的叢集IP位址。
* * Volume ID*：系統產生的相關Volume ID。
* *最小IOPS*：目前磁碟區的IOPS QoS下限設定。
* *最大IOPS*：目前Volume的最大IOPS QoS設定。
* *爆發IOPS*：目前Volume的最大爆發QoS設定。
* *爆發時間*：允許爆發的時間長度。


[discrete]
== 如需詳細資訊、請參閱

* https://docs.netapp.com/us-en/hci/index.html["資訊文件NetApp HCI"^]
* https://www.netapp.com/data-storage/solidfire/documentation["「元件與元素資源」頁面SolidFire"^]

