---
sidebar: sidebar 
permalink: vcp_reference_reports_alert_errors.html 
summary: 以下是系統警示清單、這些警示是資訊、警告或錯誤、可透過使用NetApp Element VMware vCenter Server適用的《報告》頁面、指出叢集的執行效能。 
keywords: netapp, hci, vcp, vcenter, element, monitor, report, alert, cluster, performance 
---
= 系統警示清單
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: media/


[role="lead"]
系統會在每個警示中報告錯誤代碼、協助您判斷系統的哪個元件遇到警示、以及產生警示的原因。您可以使用外掛程式擴充點來檢視錯誤代碼：

* 從Element vCenter外掛程式5.0開始、選取* NetApp遠端外掛程式>管理>報告>警示*。
* 對於Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《管理》>「報告」>「警示」*。


下列清單概述不同類型的系統警示。

* *驗證服務預設*
+
一或多個叢集節點上的驗證服務無法如預期運作。

+
如需協助、請聯絡NetApp支援部門。

* *可用虛擬網路IP位址低*
+
IP位址區塊中的虛擬網路位址數目很低。

+
若要解決此故障、請在虛擬網路位址區塊中新增更多IP位址。

* *區塊叢集完整*
+
可用區塊儲存空間不足、無法支援單一節點遺失。如需叢集完整度層級的詳細資訊、請參閱GetClusterFullThreshold API方法。此叢集故障表示下列其中一種情況：

+
** stage3低（警告）：已超過使用者定義的臨界值。調整叢集完整設定或新增更多節點。
** stage4 Critical（錯誤）：沒有足夠的空間可從1節點故障中恢復。不允許建立磁碟區、快照和複本。
** stage5Completely消耗（嚴重）1；不允許寫入或新的iSCSI連線。將會維持目前的iSCSI連線。寫入作業將會失敗、直到叢集新增更多容量為止。


+
若要解決此故障、請清除或刪除磁碟區、或將另一個儲存節點新增至儲存叢集。

* *區塊降級*
+
由於故障、區塊資料不再完整複寫。

+
|===


| 嚴重性 | 說明 


 a| 
警告
 a| 
只能存取兩份完整的區塊資料複本。



 a| 
錯誤
 a| 
只能存取區塊資料的單一完整複本。



 a| 
關鍵
 a| 
無法存取區塊資料的完整複本。

|===
+
*附註：*警告狀態只能在三重Helix系統上發生。

+
若要解決此故障、請還原任何離線節點或區塊服務、或聯絡NetApp支援部門以尋求協助。

* * BlockServiceTooFull*
+
區塊服務使用太多空間。

+
若要解決此故障、請新增更多已配置的容量。

* *封鎖服務不健全*
+
區塊服務偵測為不健全：

+
** 嚴重性=警告：不採取任何行動。此警告期間將以cTimeDuntilBSIsKledMSec=330000毫秒為單位過期。
** 嚴重性=錯誤：系統會自動解除委任資料、並將其資料重新複寫至其他正常磁碟機。
** 嚴重性=重大：數個節點上的區塊服務故障、大於或等於複寫數（2個用於雙螺旋曲線）。資料無法使用、且無法完成Bin同步。
+
檢查網路連線問題和硬體錯誤。如果特定的硬體元件故障、將會發生其他故障。當區塊服務可供存取或服務已停用時、故障將會清除。



* * BMCselfTestFailed*
+
基礎板管理控制器（BMC）自我測試失敗。

+
如需協助、請聯絡NetApp支援部門。

+
在升級至Element 12.5或更新版本期間 `BmcSelfTestFailed` 如果節點的BMC已存在故障、或是節點的BMC在升級期間故障、則不會產生故障。在升級期間未通過自我測試的BMC將會發出A `BmcSelfTestFailed` 整個叢集完成升級後發生警告故障。

* *時鐘ScewExceedsFault閾 值*
+
叢集主節點與呈現權杖的節點之間的時間偏差超過建議的臨界值。儲存叢集無法自動修正節點之間的時間偏移。

+
若要解決此故障、請使用網路內部的NTP伺服器、而非安裝預設值。如果您使用的是內部NTP伺服器、請聯絡NetApp支援部門以取得協助。

* *叢集CannotSync*
+
存在空間不足的情況、離線區塊儲存磁碟機上的資料無法同步至仍在使用中的磁碟機。

+
若要解決此問題、請新增更多儲存設備。

* *叢集完整*
+
儲存叢集中沒有更多可用的儲存空間。

+
若要解決此問題、請新增更多儲存設備。

* *叢集IOPSAreOverProvisions*
+
叢集IOPS已過度配置。所有最低QoS IOPS的總和大於叢集的預期IOPS。無法同時維護所有磁碟區的最低QoS。

+
若要解決此問題、請降低磁碟區的最低QoS IOPS設定。

* * CpuThermalEvent閾 值*
+
一個或多個CPU上的CPU散熱事件數超過設定的臨界值。

+
如果在十分鐘內未偵測到新的CPU熱事件、則警告將自行解決。

* *已禁用DriveSecurity失敗*
+
叢集未設定為啟用磁碟機安全性（閒置時加密）、但至少有一個磁碟機已啟用磁碟機安全性、表示停用這些磁碟機的磁碟機安全性失敗。此故障會以「警告」嚴重性記錄。

+
若要解決此故障、請查看故障詳細資料、瞭解無法停用磁碟機安全性的原因。可能的原因包括：

+
** 無法取得加密金鑰、請調查金鑰或外部金鑰伺服器的存取問題。
** 磁碟機上的停用作業失敗、請判斷是否可能取得錯誤的金鑰。


+
如果這兩個原因都不是故障原因、則可能需要更換磁碟機。

+
即使提供正確的驗證金鑰、您仍可嘗試恢復無法成功停用安全性的磁碟機。若要執行此作業、請將磁碟機移至「Available（可用）」、在磁碟機上執行安全清除、然後將其移回「Active（作用中）」、將其從系統中移除。

* *已中斷連線ClusterPair *
+
叢集配對中斷連線或設定不正確。

+
檢查叢集之間的網路連線能力。

* *已中斷RemoteNode"
+
遠端節點已中斷連線或設定不正確。

+
檢查節點之間的網路連線能力。

* *不連線SnapMirrorEndpoint *
+
遠端SnapMirror端點已中斷連線或設定不正確。

+
檢查叢集與遠端SnapMirrorEndpoint之間的網路連線能力。

* *磁碟可用*
+
叢集中有一或多個磁碟機可供使用。一般而言、所有叢集都應該新增所有磁碟機、而在可用狀態下則不新增任何磁碟機。如果此故障意外出現、請聯絡NetApp支援部門。

+
若要解決此故障、請將任何可用的磁碟機新增至儲存叢集。

* *磁碟機故障*
+
當一個或多個磁碟機發生故障時、叢集會傳回此故障、指出下列其中一種情況：

+
** 磁碟機管理程式無法存取磁碟機。
** Slice或block服務失敗次數過多、可能是因為磁碟機讀取或寫入失敗、而且無法重新啟動。
** 磁碟機遺失。
** 無法存取節點的主要服務（節點中的所有磁碟機均視為遺失/故障）。
** 磁碟機已鎖定、無法取得磁碟機的驗證金鑰。
** 磁碟機已鎖定、解除鎖定作業失敗。
+
若要解決此問題：

** 檢查節點的網路連線能力。
** 更換磁碟機。
** 確認驗證金鑰可用。


* *磁碟機健全狀況*
+
磁碟機未通過智慧型健全狀況檢查、因此磁碟機的功能會降低。此故障的嚴重性等級為「重大」：

+
** 序列磁碟機：插槽中的<序號>：<節點插槽><磁碟機插槽>未通過智慧型整體健全狀況檢查。


+
若要解決此故障、請更換磁碟機。

* *磁碟WearFault*
+
磁碟機的剩餘壽命已降至低於臨界值、但仍在運作中。此故障有兩種可能的嚴重性等級：「嚴重」和「警告」：

+
** 具有序列的磁碟機：<序號>位於插槽：<節點插槽><磁碟機插槽>具有嚴重的磨損等級。
** 具有序號的磁碟機：<序號>位於插槽：<節點插槽><磁碟機插槽>的磨損保留區不足。
+
若要解決此故障、請盡快更換磁碟機。



* *雙工叢集MasterCandidate*
+
偵測到多個儲存叢集主要候選對象。

+
如需協助、請聯絡NetApp支援部門。

* * enableDriveSecurity失敗*
+
叢集已設定為需要磁碟機安全性（閒置時加密）、但無法在至少一個磁碟機上啟用磁碟機安全性。此故障會以「警告」嚴重性記錄。

+
若要解決此故障、請查看故障詳細資料、瞭解無法啟用磁碟機安全性的原因。可能的原因包括：

+
** 無法取得加密金鑰、請調查金鑰或外部金鑰伺服器的存取問題。
** 磁碟機上的啟用作業失敗、請判斷是否可能取得錯誤的金鑰。如果這兩個原因都不是故障原因、則可能需要更換磁碟機。


+
即使提供正確的驗證金鑰、您仍可嘗試恢復無法成功啟用安全性的磁碟機。若要執行此作業、請將磁碟機移至「Available（可用）」、在磁碟機上執行安全清除、然後將其移回「Active（作用中）」、將其從系統中移除。

* *「受損」*
+
一或多個頻道群節點的網路連線或電力中斷。

+
若要解決此問題、請還原網路連線或電源。

* *例外*
+
報告的故障並非例行故障。這些故障不會自動從故障佇列中清除。

+
如需協助、請聯絡NetApp支援部門。

* *故障空間TooFull*
+
區塊服務未回應資料寫入要求。這會導致Slice服務空間不足、無法儲存失敗的寫入。

+
若要解決此故障、請還原區塊服務功能、以允許正常繼續寫入、並從分片服務清除故障空間。

* *風扇感應器*
+
風扇感測器故障或遺失。

+
若要解決此故障、請更換任何故障硬體。

* *光纖通道存取降級*
+
Fibre Channel節點在一段時間內未回應儲存叢集中的其他節點。在此狀態下、節點將被視為無回應、並產生叢集故障。

+
檢查網路連線能力。

* *光纖通道存取不可用*
+
所有Fibre Channel節點均無回應。隨即顯示節點ID。

+
檢查網路連線能力。

* * fiberChannelActiveIxL*
+
IXL Nexus數量已接近每個光纖通道節點所支援的8000個作用中工作階段上限。

+
** 最佳實務做法上限為5500。
** 警告上限為7500。
** 上限（未強制）為8192。


+
若要解決此故障、請將IXL Nexus數降至低於最佳實務做法的5500上限。

* * fiberChannelConfig*
+
此叢集故障表示下列其中一種情況：

+
** PCI插槽上有非預期的光纖通道連接埠。
** 發生非預期的Fibre Channel HBA模式。
** Fibre Channel HBA的韌體發生問題。
** 光纖通道連接埠未連線。
** 設定Fibre Channel PassthThrough時持續發生問題。


+
如需協助、請聯絡NetApp支援部門。

* *光纖通道IOPS *
+
IOPS總數已接近叢集中光纖通道節點的IOPS限制。限制如下：

+
** FC0025：每個光纖通道節點的4K區塊大小限制為450k IOPS。
** FCN001：每個光纖通道節點的4K區塊大小上限為625K OPS。


+
若要解決此故障、請在所有可用的Fibre Channel節點之間平衡負載。

* * fiberChannel靜態IxL*
+
IXL Nexus數量已接近每個光纖通道節點支援的16000個靜態工作階段上限。

+
** 最佳實務做法上限為11000。
** 警告上限為15000。
** 上限（強制）為16384。


+
若要解決此故障、請將IXL Nexus數降至低於1000的最佳實務做法上限。

* *檔案系統容量低*
+
其中一個檔案系統空間不足。

+
若要解決此故障、請在檔案系統中新增更多容量。

* *檔案系統IsReadOnly*
+
檔案系統已移至唯讀模式。

+
如需協助、請聯絡NetApp支援部門。

* * FpsDrives失 配*
+
非FIPS磁碟機已實際插入具有FIPS功能的儲存節點、或FIPS磁碟機已實際插入非FIPS儲存節點。每個節點會產生單一故障、並列出所有受影響的磁碟機。

+
若要解決此故障、請移除或更換有問題的磁碟機。

* * FpsDrivesOutOfCompliance *
+
系統偵測到在FIPS磁碟機功能啟用後、加密閒置功能已停用。當FIPS磁碟機功能已啟用、且儲存叢集中存在非FIPS磁碟機或節點時、也會產生此故障。

+
若要解決此故障、請在閒置時啟用加密、或從儲存叢集移除非FIPS硬體。

* * fpsselfTestFailure*
+
FIPS子系統在自我測試期間偵測到故障。

+
如需協助、請聯絡NetApp支援部門。

* *硬體組態不符*
+
此叢集故障表示下列其中一種情況：

+
** 組態與節點定義不符。
** 此類型節點的磁碟機大小不正確。
** 偵測到不受支援的磁碟機。可能的原因是安裝的元素版本無法辨識此磁碟機。建議更新此節點上的Element軟體。
** 磁碟機韌體不相符。
** 磁碟機加密功能狀態與節點不符。


+
如需協助、請聯絡NetApp支援部門。

* * idPCertificateExpiration*
+
用於協力廠商身分識別供應商（IDP）的叢集服務供應商SSL憑證即將到期或已過期。此故障會根據緊急程度使用下列嚴重性：

+
|===


| 嚴重性 | 說明 


 a| 
警告
 a| 
憑證將在30天內過期。



 a| 
錯誤
 a| 
憑證將在7天內過期。



 a| 
關鍵
 a| 
憑證將在3天內過期或已過期。

|===
+
若要解決此故障、請在SSL憑證過期之前更新。使用Update IdpConfiguration API方法 `refreshCertificateExpirationTime=true` 以提供更新的SSL憑證。

* *不一致的BondModes *
+
VLAN裝置上的連結模式遺失。此故障會顯示預期的債券模式和目前使用的債券模式。



* *不一致的Mttus *
+
此叢集故障表示下列其中一種情況：

+
** Bond1G不相符：在Bond1G介面上偵測到不一致的MTU。
** Bond10G不符：在Bond10G介面上偵測到不一致的MTU。


+
此故障會顯示有問題的節點、以及相關的MTU值。

* *不一致的RoutingRules *
+
此介面的路由規則不一致。

* *不一致的SubnetMask*
+
VLAN裝置上的網路遮罩與內部記錄的VLAN網路遮罩不符。此故障會顯示預期的網路遮罩和目前使用的網路遮罩。

* *不可修正的BondPortCount*
+
連結連接埠數量不正確。

* *不驗證配置dFibreChannelNodeCount*
+
兩個預期的光纖通道節點連線之一已降級。僅連接一個光纖通道節點時、就會出現此故障。

+
若要解決此故障、請檢查叢集網路連線和網路纜線、並檢查是否有故障的服務。如果沒有網路或服務問題、請聯絡NetApp支援部門以更換光纖通道節點。

* * irqBalanceFailed*
+
嘗試平衡中斷時發生例外狀況。

+
如需協助、請聯絡NetApp支援部門。

* * kmipCertificateFault*
+
** 根憑證授權單位（CA）憑證即將到期。
+
若要解決此錯誤、請從根CA取得到期日至少30天的新憑證、並使用ModifyKeyServerKmip提供更新的根CA憑證。

** 用戶端憑證即將到期。
+
若要解決此錯誤、請使用GetClientCertificateSigningRequest建立新的CSR、並簽署以確保新的到期日至少為30天、然後使用ModifyKeyServerKmip以新的憑證取代即將到期的KMIP用戶端憑證。

** 根憑證授權單位（CA）憑證已過期。
+
若要解決此錯誤、請從根CA取得到期日至少30天的新憑證、並使用ModifyKeyServerKmip提供更新的根CA憑證。

** 用戶端憑證已過期。
+
若要解決此錯誤、請使用GetClientCertificateSigningRequest建立新的CSR、並簽署以確保新的到期日至少為30天、然後使用ModifyKeyServerKmip以新的憑證取代過期的KMIP用戶端憑證。

** 根憑證授權單位（CA）憑證錯誤。
+
若要解決此錯誤、請檢查是否提供正確的憑證、並視需要從根CA重新取得憑證。使用ModifyKeyServerKmip安裝正確的KMIP用戶端憑證。

** 用戶端憑證錯誤。
+
若要解決此故障、請檢查是否安裝了正確的KMIP用戶端憑證。用戶端憑證的根CA應安裝在EKS上。使用ModifyKeyServerKmip安裝正確的KMIP用戶端憑證。



* * kmipServerFault*
+
** 連線失敗
+
若要解決此故障、請檢查外部金鑰伺服器是否可透過網路連線及存取。使用TestKeyServerKimp和TestKeyProviderKmip來測試連線。

** 驗證失敗
+
若要解決此錯誤、請檢查是否使用正確的根CA和KMIP用戶端憑證、以及私密金鑰和KMIP用戶端憑證是否相符。

** 伺服器錯誤
+
若要解決此故障、請查看錯誤的詳細資料。根據傳回的錯誤、可能需要在外部金鑰伺服器上進行疑難排解。



* *記憶體EccThreshold *
+
偵測到大量可修正或不可修正的ECC錯誤。此故障會根據緊急程度使用下列嚴重性：

+
|===


| 活動 | 嚴重性 | 說明 


 a| 
單一DIMM cErrorCount達到cDimmCorrectable勘 誤表錯誤臨界值。
 a| 
警告
 a| 
DIMM上可修正的ECC記憶體錯誤超過臨界值：<Processor ><DIMM插槽>



 a| 
在cErrorFaultTimers過期之前、單一DIMM cErrorCount會維持在cDimmCorrectable勘 誤表臨界值以上。
 a| 
錯誤
 a| 
DIMM上可修正的ECC記憶體錯誤超過臨界值：<Processor ><DIMM>



 a| 
記憶體控制器報告cErrorCount高於cMemrCorrectable勘 誤表WarnThreshold、並指定cMemrCorrectable勘 誤表時間長度。
 a| 
警告
 a| 
記憶體控制器上可修正的ECC記憶體錯誤超過臨界值：<Processor><Memory Controller>



 a| 
記憶體控制器會回報cErrorCount高於cMemrCorrectable勘 誤表臨界值、直到記憶體控制器的cErrorFaultTimers過期為止。
 a| 
錯誤
 a| 
DIMM上可修正的ECC記憶體錯誤超過臨界值：<Processor ><DIMM>



 a| 
單一DIMM報告uErrorCount高於零、但小於cDimmUnrectable勘 誤錯誤臨界值。
 a| 
警告
 a| 
在DIMM上偵測到不可修正的ECC記憶體錯誤：<Processor（處理器）><DIMM插槽>



 a| 
單一DIMM報告的uErrorCount至少為cDimmUnrectable勘 誤錯誤臨界值。
 a| 
錯誤
 a| 
在DIMM上偵測到不可修正的ECC記憶體錯誤：<Processor（處理器）><DIMM插槽>



 a| 
記憶體控制器回報uErrorCount大於零、但小於cMemcableErrFaultThreshold。
 a| 
警告
 a| 
在記憶體控制器上偵測到不可修正的ECC記憶體錯誤：<Processor（處理器）><Memory Controller（記憶體控制器）>



 a| 
記憶體控制器報告的uErrorCount至少為cMemCtlrUnrectable勘 誤錯誤臨界值。
 a| 
錯誤
 a| 
在記憶體控制器上偵測到不可修正的ECC記憶體錯誤：<Processor（處理器）><Memory Controller（記憶體控制器）>

|===
+
若要解決此故障、請聯絡NetApp支援部門以尋求協助。

* *記憶體使用臨界值*
+
記憶體使用量高於正常值。此故障會根據緊急程度使用下列嚴重性：

+

NOTE: 如需故障類型的詳細資訊、請參閱錯誤故障中的*詳細資料*標題。

+
|===


| 嚴重性 | 說明 


 a| 
警告
 a| 
系統記憶體不足。



 a| 
錯誤
 a| 
系統記憶體非常不足。



 a| 
關鍵
 a| 
系統記憶體已完全耗用。

|===
+
若要解決此故障、請聯絡NetApp支援部門以尋求協助。

* * metadata ClusterFull*
+
可用的中繼資料儲存空間不足、無法支援單一節點遺失。如需叢集完整度層級的詳細資訊、請參閱GetClusterFullThreshold API方法。此叢集故障表示下列其中一種情況：

+
** stage3低（警告）：已超過使用者定義的臨界值。調整叢集完整設定或新增更多節點。
** stage4 Critical（錯誤）：沒有足夠的空間可從1節點故障中恢復。不允許建立磁碟區、快照和複本。
** stage5Completely消耗（嚴重）1；不允許寫入或新的iSCSI連線。將會維持目前的iSCSI連線。寫入作業將會失敗、直到叢集新增更多容量為止。清除或刪除資料、或新增更多節點。


+
若要解決此故障、請清除或刪除磁碟區、或將另一個儲存節點新增至儲存叢集。

* * mtuChecksum故障*
+
網路裝置未設定適當的MTU大小。

+
若要解決此故障、請確定所有網路介面和交換器連接埠均已設定為巨型框架（MTU大小高達9000位元組）。

* *網路組態*
+
此叢集故障表示下列其中一種情況：

+
** 預期介面不存在。
** 存在重複的介面。
** 已設定的介面已關閉。
** 需要重新啟動網路。


+
如需協助、請聯絡NetApp支援部門。

* *無可用虛擬網路IP位點*
+
IP位址區塊中沒有可用的虛擬網路位址。

+
** 虛擬網路ID #標記（\##）沒有可用的儲存IP位址。無法將其他節點新增至叢集。


+
若要解決此故障、請在虛擬網路位址區塊中新增更多IP位址。

* *節點硬體預設（網路介面<name>當機或纜線拔下）*
+
網路介面已關閉或纜線已拔下。

+
若要解決此故障、請檢查節點或節點的網路連線能力。

* *節點硬體預設（磁碟機加密功能狀態與插槽<節點插槽><磁碟機插槽>*中磁碟機的節點加密功能狀態不符）*
+
磁碟機的加密功能與安裝的儲存節點不符。

* 此節點類型的磁碟機插槽<節點插槽><磁碟機插槽>的磁碟機大小<實際大小>不正確-預期<預期大小>*
+
儲存節點所含的磁碟機大小不正確。

* *節點硬體預設（在插槽<節點插槽><磁碟機插槽>中偵測到不受支援的磁碟機；磁碟機統計資料與健全狀況資訊將無法使用）*
+
儲存節點包含不支援的磁碟機。

* *節點硬體預設（插槽<節點插槽><磁碟機插槽>中的磁碟機應使用韌體版本<預期版本>、但使用不支援的版本<實際版本>*）
+
儲存節點包含執行不受支援韌體版本的磁碟機。

* *節點維護模式*
+
節點已置於維護模式。此故障會根據緊急程度使用下列嚴重性：

+
|===


| 嚴重性 | 說明 


 a| 
警告
 a| 
表示節點仍處於維護模式。



 a| 
錯誤
 a| 
表示維護模式無法停用、很可能是因為執行中的標準失敗。

|===
+
若要解決此故障、請在維護完成後停用維護模式。如果錯誤層級故障持續發生、請聯絡NetApp支援部門以尋求協助。

* *節點離線*
+
Element軟體無法與指定節點通訊。檢查網路連線能力。

* *註釋使用LACPBondMode*
+
未設定LACP連結模式。

+
若要解決此問題、請在部署儲存節點時使用LACP連結；如果未啟用LACP並未正確設定、用戶端可能會遇到效能問題。

* * ntpServerUnreachable *
+
儲存叢集無法與指定的NTP伺服器通訊。

+
若要解決此故障、請檢查NTP伺服器、網路和防火牆的組態。

* * ntpTimezNotInSync*
+
儲存叢集時間與指定NTP伺服器時間之間的差異過大。儲存叢集無法自動修正差異。

+
若要解決此故障、請使用網路內部的NTP伺服器、而非安裝預設值。如果您使用的是內部NTP伺服器、但問題仍然存在、請聯絡NetApp支援部門以尋求協助。

* * nvramDevice狀態*
+
NVRAM裝置發生錯誤、故障或故障。此故障具有下列嚴重性：

+
|===


| 嚴重性 | 說明 


 a| 
警告
 a| 
硬體偵測到警告。這種情況可能是暫時性的、例如溫度警告。

** nvmLifestime錯誤
** nvmLifestimeStatus
** energySourceLifestimeStatus
** energySourceTemperatureStatus
** warningTholdExceeded




 a| 
錯誤
 a| 
硬體偵測到錯誤或嚴重狀態。叢集主要會嘗試從作業中移除分片磁碟機（這會產生磁碟機移除事件）。如果次要Slice服務無法使用、則不會移除磁碟機。除了「警告層級錯誤：

** NVRAM裝置掛載點不存在。
** NVRAM裝置分割區不存在。
** 存在NVRAM設備分區、但未掛載。




 a| 
關鍵
 a| 
硬體偵測到錯誤或嚴重狀態。叢集主要會嘗試從作業中移除分片磁碟機（這會產生磁碟機移除事件）。如果次要Slice服務無法使用、則不會移除磁碟機。

** 持續性
** ArmStatusSaveNArmed
** cSaveStatus錯誤


|===
+
更換節點中任何故障的硬體。如果這無法解決問題、請聯絡NetApp支援部門以尋求協助。

* *電源供應錯誤*
+
此叢集故障表示下列其中一種情況：

+
** 電源供應器不存在。
** 電源供應器故障。
** 電源供應器輸入遺失或超出範圍。


+
若要解決此故障、請確認所有節點均已提供備援電源。如需協助、請聯絡NetApp支援部門。

* *資源配置空間TooFull*
+
叢集的整體已配置容量太滿。

+
若要解決此故障、請新增更多已配置空間、或刪除和清除磁碟區。

* *移除其他同步延遲*
+
已超過設定的非同步複寫延遲。檢查叢集之間的網路連線能力。

* * remoteReplClusterFull*
+
由於目標儲存叢集太滿、因此磁碟區已暫停遠端複寫。

+
若要解決此故障、請釋放目標儲存叢集上的部分空間。

* *遠端修復SnapshotClusterFull*
+
由於目標儲存叢集太滿、因此磁碟區已暫停遠端複寫快照。

+
若要解決此故障、請釋放目標儲存叢集上的部分空間。

* *遠端服務重新快照所激發的限制*
+
由於目標儲存叢集磁碟區已超過快照限制、因此磁碟區已暫停遠端複寫快照。

+
若要解決此故障、請增加目標儲存叢集的快照限制。

* *排程行動錯誤*
+
一或多個排程活動已執行、但失敗。

+
如果排程的活動再次執行並成功、排程的活動已刪除、或活動已暫停並恢復、則會清除故障。

* * sensorReadingFailed*
+
感應器無法與基礎板管理控制器（BMC）通訊。

+
如需協助、請聯絡NetApp支援部門。

* *服務未執行*
+
所需的服務未執行。

+
如需協助、請聯絡NetApp支援部門。

* *交叉分析eServiceTooFull*
+
分片服務的已配置容量太少、無法分配給它。

+
若要解決此故障、請新增更多已配置的容量。

* *交叉分析eServiceUnHealth*
+
系統偵測到Slice服務不健全、並正在自動解除委任。

+
** 嚴重性=警告：不採取任何行動。此警告期間將於6分鐘後到期。
** 嚴重性=錯誤：系統會自動解除委任資料、並將其資料重新複寫至其他正常磁碟機。


+
檢查網路連線問題和硬體錯誤。如果特定的硬體元件故障、將會發生其他故障。當可存取Slice服務或服務已停用時、故障將會清除。

* * shEnabled*
+
SSH服務會在儲存叢集中的一個或多個節點上啟用。

+
若要解決此故障、請停用適當節點或節點上的SSH服務、或聯絡NetApp支援部門以尋求協助。

* * slCertificateExpiration*
+
與此節點相關的SSL憑證即將到期或已過期。此故障會根據緊急程度使用下列嚴重性：

+
|===


| 嚴重性 | 說明 


 a| 
警告
 a| 
憑證將在30天內過期。



 a| 
錯誤
 a| 
憑證將在7天內過期。



 a| 
關鍵
 a| 
憑證將在3天內過期或已過期。

|===
+
若要解決此問題、請更新SSL憑證。如有需要、請聯絡NetApp支援部門以取得協助。

* * strandedCapacity *
+
單一節點佔儲存叢集容量的一半以上。

+
為了維持資料備援、系統會減少最大節點的容量、使部分區塊容量無法使用（未使用）。

+
若要解決此故障、請將更多磁碟機新增至現有的儲存節點、或將儲存節點新增至叢集。

* *誘惑感測器*
+
溫度感測器報告的溫度高於正常溫度。此故障可與PowerSupplyError或FanSensor故障一起觸發。

+
若要解決此故障、請檢查儲存叢集附近是否有氣流障礙。如有需要、請聯絡NetApp支援部門以取得協助。

* *升級*
+
升級已進行24小時以上。

+
若要解決此問題、請繼續升級、或聯絡NetApp支援部門以尋求協助。

* *不負責服務*
+
服務變得無回應。

+
如需協助、請聯絡NetApp支援部門。

* *虛擬化網路組態*
+
此叢集故障表示下列其中一種情況：

+
** 介面不存在。
** 介面上的命名空間不正確。
** 網路遮罩不正確。
** IP位址不正確。
** 介面未啟動且未執行。
** 節點上有多餘的介面。


+
如需協助、請聯絡NetApp支援部門。

* *卷降級*
+
次要磁碟區尚未完成複寫與同步處理。同步完成時、訊息會清除。

* * Volume離線*
+
儲存叢集中的一個或多個磁碟區已離線。也會出現* Volume Degraded*故障。

+
如需協助、請聯絡NetApp支援部門。


