---
sidebar: sidebar 
permalink: vcp_task_protect_remote_replication.html 
summary: 即時複寫可快速建立Volume資料的遠端複本。 
keywords: netapp, hci, vcp, vcenter, element, protect, replication, remote, cluster 
---
= 在叢集之間執行遠端複寫
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
對於執行NetApp Element Real-Software的叢集、即時複寫功能可讓您快速建立Volume資料的遠端複本。您可以將儲存叢集與最多四個其他儲存叢集配對。

您可以從叢集配對中的任一叢集同步或非同步複寫磁碟區資料、以進行容錯移轉和容錯回復。您必須先配對兩NetApp Element 個叢集、然後在每個叢集上配對磁碟區、才能使用即時遠端複寫功能。

.您需要的產品
* 請確定您已將至少一個叢集新增至外掛程式。
* 確保已配對叢集的管理和儲存網路上的所有節點IP位址都會彼此路由傳送。
* 確保所有配對節點的MTU都相同、而且叢集之間支援端點對端點。
* 確保NetApp Element 叢集上的各個版本不超過一個主要版本。如果差異較大、則必須升級其中一個叢集、才能執行資料複寫。



NOTE: WAN加速器設備未經NetApp認證、無法在複寫資料時使用。如果在複寫資料的兩個叢集之間部署、這些應用裝置可能會干擾壓縮和重複資料刪除。在正式作業環境中部署任何WAN加速器設備之前、請務必完全符合其效果。

.步驟
. <<配對叢集>>
. <<配對磁碟區>>
. <<驗證Volume複寫>>
. <<複寫後刪除磁碟區關係>>
. <<管理Volume關係>>




== 配對叢集

您必須將兩個叢集配對、作為使用即時複寫功能的第一步。配對並連線兩個叢集之後、您可以將一個叢集上的作用中磁碟區設定為持續複寫到第二個叢集、以提供持續的資料保護（CDP）。

如果兩個叢集都有叢集管理存取權、您可以使用目標叢集的MVIP來配對來源與目標叢集。如果叢集配對中的某個叢集僅有叢集可供使用叢集管理存取、則可在目標叢集上使用配對金鑰來完成叢集配對。

.您需要的產品
* 您需要叢集管理權限才能配對一個或兩個叢集。
* 確保叢集之間的往返延遲低於2000毫秒。
* 確保NetApp Element 叢集上的各個版本不超過一個主要版本。
* 確保配對叢集上的所有節點IP都彼此路由傳送。



NOTE: 叢集配對需要在管理網路上的節點之間建立完整連線。複寫需要在儲存叢集網路上的個別節點之間建立連線。

您可以將一個NetApp Element 不含任何一個的叢集與最多四個其他叢集配對、以複寫磁碟區。您也可以將叢集群組內的叢集彼此配對。

請選擇下列其中一種方法：

* <<使用已知認證配對叢集>>
* <<將叢集與配對金鑰配對>>




=== 使用已知認證配對叢集

您可以使用一個叢集的MVIP與另一個叢集建立連線、配對兩個叢集以進行即時複寫。若要使用此方法、必須在兩個叢集上存取叢集管理。

.關於這項工作
叢集管理使用者名稱和密碼用於驗證叢集存取、然後才能配對叢集。

如果不知道MVIP、或無法存取叢集、您可以產生配對金鑰、然後使用金鑰配對兩個叢集、來配對叢集。如需相關指示、請參閱 <<將叢集與配對金鑰配對>>。

.步驟
. 在vSphere Web Client中、開啟* Protection（保護）*索引標籤：
+
** 從Element vCenter外掛程式5.0開始、選取* NetApp Element 《遠端外掛程式》>「組態」>「Protection」*。
** 針對Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《組態》>「保護*」。
+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。



. 選取*叢集配對*子索引標籤。
. 選取*建立叢集配對*。
. 選取下列其中一項：
+
** *已登錄叢集*：如果配對的遠端叢集是由元素vCenter外掛程式的相同執行個體所控制、請選取此項目。
** *可認證的叢集*：如果遠端叢集的認證資料不在元件vCenter外掛程式組態範圍內、請選取此選項。


. 如果選擇*已註冊的叢集*、請從可用叢集清單中選取叢集、然後按一下*配對*。
. 如果您選取*可認證的叢集*、請執行下列動作：
+
.. 輸入遠端叢集MVIP位址。
.. 輸入叢集管理員使用者名稱。
.. 輸入叢集管理員密碼。
.. 選取*開始配對*。


. 工作完成後、您會看到「叢集配對」頁面、請確認叢集配對已連線。
. （選用）在遠端叢集上、使用元素UI或外掛程式擴充點來驗證叢集配對是否已連線：
+
** 從Element vCenter外掛程式5.0開始、選取* NetApp Element 《遠端外掛程式》>「管理」>「保護」>「叢集配對」*。
** 對於Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《Management》（英文）>「Protection」（保護）>「Cluster Pair*」（叢集配對*）。






=== 將叢集與配對金鑰配對

如果您擁有本機叢集的叢集管理存取權、但無法存取遠端叢集、則可使用配對金鑰配對叢集。配對金鑰會在本機叢集上產生、然後安全地傳送至遠端站台的叢集管理、以建立連線並完成叢集配對、以進行即時複寫。

本程序說明在本機和遠端站台上使用vCenter的兩個叢集之間進行叢集配對。對於非由vCenter外掛程式控制的叢集、您也可以選擇 https://docs.netapp.com/us-en/element-software/storage/task_replication_pair_cluster_using_pairing_key.html["啟動或完成叢集配對"] 使用元素Web UI。

[[open_protection_tab]]
.步驟
. 在包含本機叢集的vCenter中、開啟* Protection（保護）*索引標籤：
+
** 從Element vCenter外掛程式5.0開始、選取* NetApp Element 《遠端外掛程式》>「管理」>「Protection」*。
** 對於Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《Management》（*）>「Protection」（保護）*。
+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。



. 選取*叢集配對*子索引標籤。
. 選取*建立叢集配對*。
. 選擇*不可存取的叢集*。
. 選取*產生金鑰*。
+

NOTE: 此動作會產生配對的文字金鑰、並在本機叢集上建立未設定的叢集配對。如果您未完成此程序、則需要手動刪除叢集配對。

. 將叢集配對金鑰複製到剪貼簿。
. 選擇*關閉*。
. 讓遠端叢集站台的叢集管理員可以存取配對金鑰。
+

NOTE: 叢集配對金鑰包含MVIP的版本、使用者名稱、密碼和資料庫資訊、以允許遠端複寫的磁碟區連線。此金鑰應以安全的方式處理、而非以允許意外或不安全地存取使用者名稱或密碼的方式儲存。

+

IMPORTANT: 請勿修改配對金鑰中的任何字元。如果修改金鑰、金鑰就會變成無效。

. 從包含遠端叢集的vCenter、 <<open_protection_tab,開啟「Protection（保護）」索引標籤>>。
+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。

+

NOTE: 您也可以使用Element UI完成配對。

. 選取*叢集配對*子索引標籤。
. 選取*完整叢集配對*。
+

NOTE: 等待載入微調器消失、再繼續下一步。如果配對程序期間發生非預期的錯誤、請檢查並手動刪除本機和遠端叢集上任何未設定的叢集配對、然後再次執行配對。

. 將本機叢集的配對金鑰貼到*叢集配對金鑰*欄位。
. 選擇*配對叢集*。
. 工作完成後、您會看到「*叢集配對*」頁面、請確認叢集配對已連線。
. 若要驗證叢集配對是否已連線、請在遠端叢集上執行 <<open_protection_tab,開啟「Protection（保護）」索引標籤>> 或使用Element UI。




=== 驗證叢集配對連線

叢集配對完成後、您可能需要驗證叢集配對連線、以確保複寫成功。

.步驟
. 在本機叢集上、選取*資料保護*>*叢集配對*。
. 驗證是否已連接叢集配對。
. 瀏覽回本機叢集和*叢集配對*視窗、確認已連接叢集配對。




== 配對磁碟區

在叢集配對中建立叢集之間的連線之後、您可以將一個叢集上的磁碟區與配對中另一個叢集上的磁碟區配對。

您可以使用下列其中一種方法配對Volume：

* <<使用已知認證配對磁碟區>>：兩個叢集都使用已知的認證資料
* <<使用配對金鑰配對磁碟區>>：如果叢集認證僅在來源叢集上可用、請使用配對金鑰。
* <<建立目標磁碟區、並將其與本機磁碟區配對>>：如果您知道兩個叢集的認證資料、請在遠端叢集上建立複寫目標磁碟區、以便與來源叢集配對。


建立磁碟區配對關係之後、您必須識別哪個磁碟區是複寫目標：

* <<將複寫來源和目標指派給配對的磁碟區>>


.您需要的產品
* 您應該已經在叢集配對中的叢集之間建立連線。
* 您必須擁有叢集管理權限、才能配對一個或兩個叢集。




=== 使用已知認證配對磁碟區

您可以將本機磁碟區與遠端叢集上的其他磁碟區配對。如果叢集管理存取權可同時存取要配對磁碟區的兩個叢集、請使用此方法。此方法會使用遠端叢集上磁碟區的Volume ID來啟動連線。

.開始之前
* 您擁有遠端叢集的叢集管理認證。
* 請確定包含磁碟區的叢集已配對。
* 除非您打算在此過程中建立新的Volume、否則您知道遠端Volume ID。
* 如果您打算將本機磁碟區設為來源、請確定該磁碟區的存取模式已設為讀取/寫入。


.步驟
. 在包含本機叢集的vCenter中、開啟*管理*索引標籤：
+
** 從Element vCenter外掛程式5.0開始、選取* NetApp Element 《遠端外掛程式》>「管理」>「管理」*。
** 對於Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《Management》（*《管理》）>「Management」（管理）*。


+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。

. 選取* Volumes（磁碟區）*子索引標籤。
. 從* Active*檢視中、選取您要配對之Volume的核取方塊。
. 選取*「動作*」。
. 選取* Volume Pair*。
. 選取下列其中一項：
+
** * Volume Creation *：若要在遠端叢集上建立複寫目標磁碟區、請選取此選項。此方法只能用於由元件vCenter外掛程式控制的遠端叢集。
** * Volume選擇*：如果目標Volume的遠端叢集是由元件vCenter外掛程式控制、請選取此選項。
** * Volume ID*：如果目標磁碟區的遠端叢集擁有元素vCenter外掛程式組態以外的已知認證、請選取此選項。


. 選取複寫模式：
+
** *即時（同步）*：寫入作業會在來源叢集和目標叢集上提交後、確認寫入至用戶端。
** *即時（非同步）*：寫入作業在來源叢集上提交後、便會對用戶端進行認可。
** *僅快照*：僅複寫在來源叢集上建立的快照。不會複寫來源Volume的作用中寫入內容。


. 如果您選取*建立Volume *作為配對模式選項、請執行下列步驟：
+
.. 從下拉式清單中選取配對的叢集。
+

NOTE: 此動作會填入叢集上的可用帳戶、以便在下一個步驟中選取。

.. 在目標叢集上選取複寫目標磁碟區的帳戶。
.. 輸入複寫目標磁碟區名稱。
+

NOTE: 在此程序期間無法調整Volume大小。



. 如果您選取* Volume selection *作為配對模式選項、請執行下列步驟：
+
.. 選取配對的叢集。
+

NOTE: 此動作會填入叢集上要在下一步中選取的可用磁碟區。

.. （可選）如果要將遠端Volume設為Volume配對中的目標、請選取*將遠端Volume設為Replication Target *（複寫目標*）選項。本機磁碟區若設為讀取/寫入、即會成為配對中的來源。
+

IMPORTANT: 如果您將現有磁碟區指派為複寫目標、則該磁碟區上的資料將會遭到覆寫。最佳實務做法是使用新的磁碟區作為複寫目標。

+

NOTE: 您也可以稍後在配對程序中從* Volumes *>* Actions *>* Edit *指派複寫來源和目標。您必須指派來源和目標才能完成配對。

.. 從可用磁碟區清單中選取一個磁碟區。


. 如果您選取* Volume ID*作為配對模式選項、請執行下列步驟：
+
.. 從下拉式清單中選取配對的叢集。
.. 如果叢集未以外掛程式登錄、請輸入叢集管理員使用者ID和叢集管理員密碼。
.. 輸入Volume ID。
.. 如果要將遠端Volume設為Volume配對中的目標、請選取*將遠端Volume設為Replication Target *（複寫目標*）選項。本機磁碟區若設為讀取/寫入、即會成為配對中的來源。
+

IMPORTANT: 如果您將現有磁碟區指派為複寫目標、則該磁碟區上的資料將會遭到覆寫。最佳實務做法是使用新的磁碟區作為複寫目標。

+

NOTE: 您也可以稍後在配對程序中從* Volumes *>* Actions *>* Edit *指派複寫來源和目標。您必須指派來源和目標才能完成配對。



. 選擇*配對*。
+

NOTE: 確認配對之後、兩個叢集便會開始連接磁碟區的程序。在配對過程中、您可以在Volume Pairs（Volume Pairs）頁面的Volume Status（Volume狀態）欄中看到進度訊息。

+

NOTE: 如果您尚未將磁碟區指派為複寫目標、配對組態將不完整。磁碟區配對會顯示PausedMisconfigured、直到指派磁碟區配對來源和目標為止。您必須指派來源和目標、才能完成Volume配對。

. 在任一叢集上選取* Protection *>* Volume Pair*。
. 驗證Volume配對的狀態。




=== 使用配對金鑰配對磁碟區

您可以使用配對金鑰、將本機Volume與遠端叢集上的其他Volume配對。如果只有來源叢集的叢集管理存取權、請使用此方法。此方法會產生配對金鑰、可用於遠端叢集以完成Volume配對。

.開始之前
* 請確定包含磁碟區的叢集已配對。
* *最佳實務做法*：將來源磁碟區設為「讀取/寫入」、將目標磁碟區設為「複寫目標」。目標磁碟區不應包含任何資料、且應具有來源磁碟區的確切特性、例如大小、512e設定和QoS組態。如果您將現有磁碟區指派為複寫目標、則該磁碟區上的資料將會遭到覆寫。目標Volume的大小可能大於或等於來源Volume、但不能變小。


.關於這項工作
本程序說明在本機和遠端站台上使用vCenter的兩個磁碟區之間進行Volume配對。對於非由vCenter外掛程式控制的磁碟區、您可以使用元素Web UI來啟動或完成Volume配對。

如需從Element Web UI開始或完成Volume配對的指示、請參閱 https://docs.netapp.com/us-en/element-software/storage/task_replication_pair_volumes_using_a_pairing_key.html["軟體文件NetApp Element"^]。


NOTE: Volume配對金鑰包含加密版本的Volume資訊、可能包含敏感資訊。只能以安全的方式共用此金鑰。

[[open_management]]
.步驟
. 在包含本機叢集的vCenter中、開啟*管理*索引標籤：
+
** 從Element vCenter外掛程式5.0開始、選取* NetApp Element 《遠端外掛程式》>「管理」>「管理」*。
** 對於Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《Management》（*《管理》）>「Management」（管理）*。
+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。



. 選取* Volumes（磁碟區）*子索引標籤。
. 從* Active*檢視中、選取您要配對之Volume的核取方塊。
. 選取*「動作*」。
. 選取* Volume Pair*。
. 選擇*不可存取的叢集*。
. 選取複寫模式：
+
** *即時（同步）*：寫入作業會在來源叢集和目標叢集上提交後、確認寫入至用戶端。
** *即時（非同步）*：寫入作業在來源叢集上提交後、便會對用戶端進行認可。
** *僅快照*：僅複寫在來源叢集上建立的快照。不會複寫來源Volume的作用中寫入內容。


. 選取*產生金鑰*。
+

NOTE: 此動作會產生配對的文字金鑰、並在本機叢集上建立未設定的Volume配對。如果您不這麼做、則需要手動刪除Volume配對。

. 將配對金鑰複製到剪貼簿。
. 選擇*關閉*。
. 讓遠端叢集站台的叢集管理員可以存取配對金鑰。
+

NOTE: Volume配對金鑰應以安全的方式處理、而非以允許意外或不安全存取的方式儲存。

+

IMPORTANT: 請勿修改配對金鑰中的任何字元。如果修改金鑰、金鑰就會變成無效。

. 從包含遠端叢集的vCenter、 <<open_management,開啟「管理」索引標籤>>。
+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。

. 選取* Volumes（磁碟區）*子索引標籤。
. 從* Active*檢視中、選取您要配對之磁碟區的核取方塊。
. 選取*「動作*」。
. 選取* Volume Pair*。
. 選取*完整叢集配對*。
. 將另一個叢集的配對金鑰貼到*配對金鑰*方塊中。
. 選取*完整配對*。
+

NOTE: 確認配對之後、兩個叢集便會開始連接磁碟區的程序。在配對過程中、您可以在Volume Pairs（Volume Pairs）頁面的Volume Status（Volume狀態）欄中看到進度訊息。如果配對程序期間發生非預期的錯誤、請檢查並手動刪除本機和遠端叢集上任何未設定的叢集配對、然後再次執行配對。

+

IMPORTANT: 如果您尚未將磁碟區指派為複寫目標、配對組態將不完整。磁碟區配對會顯示「PausedMisconfigured」、直到指派磁碟區配對來源和目標為止。您必須指派來源和目標、才能完成Volume配對。

. 在任一叢集上選取* Protection *>* Volume Pair*。
. 驗證Volume配對的狀態。
+

NOTE: 使用配對金鑰配對的Volume會在遠端位置完成配對程序後顯示。





=== 建立目標磁碟區、並將其與本機磁碟區配對

您可以將兩個或多個本機磁碟區與遠端叢集上的相關目標磁碟區配對。此程序會針對您選取的每個本機來源Volume、在遠端叢集上建立複寫目標磁碟區。如果叢集管理存取權可同時存取要配對磁碟區的兩個叢集、且遠端叢集由外掛程式控制、請使用此方法。

此方法使用遠端叢集上每個磁碟區的Volume ID來起始一或多個連線。

.開始之前
* 確保您擁有遠端叢集的叢集管理認證。
* 請確定內含磁碟區的叢集已使用外掛程式配對。
* 確保遠端叢集由外掛程式控制。
* 確保每個本機磁碟區的存取模式均設定為讀取/寫入。


.步驟
. 在包含本機叢集的vCenter中、開啟*管理*索引標籤：
+
** 從Element vCenter外掛程式5.0開始、選取* NetApp Element 《遠端外掛程式》>「管理」>「管理」*。
** 對於Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《Management》（*《管理》）>「Management」（管理）*。


+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。

. 選取* Volumes（磁碟區）*子索引標籤。
. 從* Active*檢視中、選取兩個或多個您要配對的磁碟區。
. 選取*「動作*」。
. 選取* Volume Pair*。
. 選擇*複寫模式*：
+
** *即時（同步）*：寫入作業會在來源叢集和目標叢集上提交後、確認寫入至用戶端。
** *即時（非同步）*：寫入作業在來源叢集上提交後、便會對用戶端進行認可。
** *僅快照*：僅複寫在來源叢集上建立的快照。不會複寫來源Volume的作用中寫入內容。


. 從下拉式清單中選取配對的叢集。
. 在目標叢集上選取複寫目標磁碟區的帳戶。
. （選用）在目標叢集上輸入新磁碟區名稱的前置或後置字元。
+

NOTE: 此時會出現一個含有修改名稱的範例Volume名稱。

. 選取*建立配對*。
+

NOTE: 確認配對之後、兩個叢集便會開始連接磁碟區的程序。在配對過程中、您可以在Volume Pairs（Volume Pairs）頁面的Volume Status（Volume狀態）欄中看到進度訊息。程序完成後、會在遠端叢集上建立並連線新的目標磁碟區。

. 在任一叢集上選取* Protection *>* Volume Pair*。
. 驗證Volume配對的狀態。




=== 將複寫來源和目標指派給配對的磁碟區

如果您在磁碟區配對期間未將磁碟區指派為複寫目標、則組態不會完成。您可以使用此程序來指派來源Volume及其複寫目標Volume。複寫來源或目標可以是Volume配對中的任一Volume。

您也可以使用此程序、在來源Volume無法使用時、將資料從來源Volume重新導向至遠端目標Volume。

.開始之前
您可以存取包含來源和目標磁碟區的叢集。

.關於這項工作
本程序說明如何在本機和遠端站台上使用vCenter、在兩個叢集之間指派來源和複寫磁碟區。對於不受vCenter外掛程式控制的磁碟區、您可以選擇 https://docs.netapp.com/us-en/element-software/storage/task_replication_assign_replication_source_and_target_to_paired_volumes.html["指派來源或複寫磁碟區"] 使用元素Web UI。

複寫來源磁碟區具有讀寫帳戶存取權。複寫目標磁碟區只能由複寫來源以讀取/寫入方式存取。

*最佳實務做法*：目標磁碟區不應包含任何資料、且應具有來源磁碟區的確切特性、例如大小、512e設定和QoS組態。目標Volume的大小可能大於或等於來源Volume、但不能變小。

.步驟
. 選取包含配對磁碟區的叢集、以作為外掛程式擴充點的複寫來源：
+
** 從* NetApp遠端外掛程式>管理*的Element vCenter外掛程式5.0開始。
** 針對Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《Management》*。


. 從Element Plug-in for vCenter Server版本的擴充點、選取*管理*索引標籤。
. 選取* Volumes（磁碟區）*子索引標籤。
. 從* Active*檢視中、選取您要編輯之Volume的核取方塊。
. 選取*「動作*」。
. 選擇*編輯*。
. 從存取下拉式清單中、選取*讀取/寫入*。
+

IMPORTANT: 如果您要反轉來源和目標指派、此動作會導致磁碟區配對顯示「暫停已設定的項目」、直到指派新的複寫目標為止。變更存取會暫停磁碟區複寫、並導致資料傳輸停止。請確定您已在兩個站台協調這些變更。

. 選擇*確定*。
. 選取包含您要作為複寫目標之配對磁碟區的叢集：
+
** 對於Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《Management》（支援管理）>「Management」（管理）*。
** 從* NetApp遠端外掛程式>管理>管理*的Element vCenter外掛程式5.0開始。


. 選取* Volumes（磁碟區）*子索引標籤。
. 從* Active*檢視中、選取您要編輯之Volume的核取方塊。
. 選取*「動作*」。
. 選擇*編輯*。
. 在*存取*下拉式清單中、選取*複寫目標*。
+

IMPORTANT: 如果您將現有磁碟區指派為複寫目標、則該磁碟區上的資料將會遭到覆寫。最佳實務做法是使用新的磁碟區作為複寫目標。

. 選擇*確定*。




== 驗證Volume複寫

複寫磁碟區之後、您應該確定來源與目標磁碟區處於作用中狀態。處於「作用中」狀態時、磁碟區會配對、資料會從來源傳送至目標磁碟區、而且資料會同步。

.步驟
. 在包含本機叢集的vCenter中、開啟* Protection（保護）*索引標籤：
+
** 從Element vCenter外掛程式5.0開始、選取* NetApp Element 《遠端外掛程式》>「管理」>「Protection」*。
** 對於Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《Management》（*）>「Protection」（保護）*。


+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。

. 選取* Volume Pair*子索引標籤。
. 驗證Volume狀態是否為「Active（作用中）」。




== 複寫後刪除磁碟區關係

複寫完成且不再需要磁碟區配對關係之後、您可以刪除磁碟區關係。

請參閱 <<刪除Volume配對>>。



== 管理Volume關係

您可以透過多種方式來管理磁碟區關係、例如暫停複寫、反轉磁碟區配對、變更複寫模式、刪除磁碟區配對、或刪除叢集配對。

* <<暫停複寫>>
* <<變更複寫模式>>
* <<刪除Volume配對>>
* <<刪除叢集配對>>




=== 暫停複寫

您可以編輯Volume Pair內容以手動暫停複寫。

.步驟
. 在包含本機叢集的vCenter中、開啟* Protection（保護）*索引標籤：
+
** 從Element vCenter外掛程式5.0開始、選取* NetApp Element 《遠端外掛程式》>「管理」>「Protection」*。
** 對於Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《Management》（*）>「Protection」（保護）*。


+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。

. 選取* Volume Pair*子索引標籤。
. 選取您要編輯之Volume配對的核取方塊。
. 選取*「動作*」。
. 選擇*編輯*。
. 手動暫停或啟動複寫程序。
+

IMPORTANT: 手動暫停或恢復磁碟區複寫會導致資料傳輸停止或恢復。請確定您已在兩個站台協調這些變更。

. 選取*儲存變更*。




=== 變更複寫模式

您可以編輯Volume配對內容、以變更Volume配對關係的複寫模式。

.步驟
. 在包含本機叢集的vCenter中、開啟* Protection（保護）*索引標籤：
+
** 從Element vCenter外掛程式5.0開始、選取* NetApp Element 《遠端外掛程式》>「管理」>「Protection」*。
** 對於Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《Management》（*）>「Protection」（保護）*。


+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。

. 選取* Volume Pair*子索引標籤。
. 選取您要編輯之Volume配對的核取方塊。
. 選取*「動作*」。
. 選擇*編輯*。
. 選取新的複寫模式：
+

IMPORTANT: 變更複寫模式會導致模式立即變更。請確定您已在兩個站台協調這些變更。

+
** *即時（同步）*：寫入作業會在來源叢集和目標叢集上提交後、確認寫入至用戶端。
** *即時（非同步）*：寫入作業在來源叢集上提交後、便會對用戶端進行認可。
** *僅快照*：僅複寫在來源叢集上建立的快照。不會複寫來源Volume的作用中寫入內容。


. 選取*儲存變更*。




=== 刪除Volume配對

若要移除兩個磁碟區之間的配對關聯、您可以刪除一個磁碟區配對。

.關於這項工作
本程序說明如何在本機和遠端站台上、使用vCenter刪除兩個磁碟區之間的Volume配對關係。

對於不受vCenter外掛程式控制的磁碟區、您也可以選擇 link:https://docs.netapp.com/us-en/element-software/storage/task_replication_delete_volume_relationship_after_replication.html["刪除磁碟區配對結束"] 使用元素Web UI。

.步驟
. 在包含本機叢集的vCenter中、開啟* Protection（保護）*索引標籤：
+
** 從Element vCenter外掛程式5.0開始、選取* NetApp Element 《遠端外掛程式》>「管理」>「Protection」*。
** 對於Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《Management》（*）>「Protection」（保護）*。


+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。

. 選取* Volume Pair*子索引標籤。
. 選取一或多個您要刪除的Volume配對。
. 選取*「動作*」。
. 選擇*刪除*。
. 確認每個Volume配對的詳細資料。
+

NOTE: 對於未由外掛程式管理的叢集、此動作只會刪除本機叢集上的磁碟區配對端點。您必須手動刪除遠端叢集的Volume配對、才能完全移除配對關係。

. （對於由外掛程式管理的叢集而言為選用）選取「Change Replication Target Access to *（將複寫目標存取權變更為*）」核取方塊、然後為複寫目標磁碟區選取新的存取模式。此新的存取模式將在Volume配對關係移除之後套用。
. 選擇*是*。




=== 刪除叢集配對

您可以使用本機和遠端站台上的vCenter、刪除兩個叢集之間的叢集配對關係。若要完全移除叢集配對關係、您必須移除本機和遠端叢集的叢集配對端點。

您可以使用vCenter外掛程式刪除叢集配對端點

對於非由vCenter外掛程式控制的叢集、您也可以選擇 link:https://docs.netapp.com/us-en/element-software/storage/task_replication_delete_cluster_pair.html["刪除叢集配對結束"] 使用元素Web UI。

.步驟
. 在包含本機叢集的vCenter中、開啟* Protection（保護）*索引標籤：
+
** 從Element vCenter外掛程式5.0開始、選取* NetApp Element 《遠端外掛程式》>「管理」>「Protection」*。
** 對於Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《Management》（*）>「Protection」（保護）*。


. 選取*叢集配對*子索引標籤。
. 選取您要刪除之叢集配對的核取方塊。
. 選取*「動作*」。
. 選擇*刪除*。
. 確認行動。
+

NOTE: 此動作只會刪除本機叢集上的叢集配對端點。您必須手動刪除遠端叢集的叢集配對、才能完全移除配對關係。

. 重複叢集配對中遠端叢集的步驟。




== Volume配對訊息與警告

您可以在外掛程式擴充點的「保護」索引標籤的「Volume Pairs」（磁碟區配對）頁面上、檢視已配對或正在配對的磁碟區資訊。從Element vCenter外掛程式5.0開始、從NetApp Element 「支援遠端外掛程式」擴充點選取「管理」索引標籤。針對Element vCenter外掛程式4.10及更早版本、請選取NetApp Element 「VMware vCenter管理」擴充點。

系統會在Volume Status（Volume狀態）欄中顯示配對與進度訊息。

* <<Volume配對訊息>>
* <<Volume配對警告>>




=== Volume配對訊息

您可以從外掛程式擴充點的「保護」索引標籤的「Volume Pairs」（磁碟區配對）頁面、檢視初始配對程序期間的訊息。這些訊息會顯示在Volume Status（Volume狀態）欄中、並可顯示在配對的來源和目標端點上。

* *暫停已中斷連線*：來源複寫或同步RPC逾時。與遠端叢集的連線已中斷。檢查與叢集的網路連線。
* *重新連線已連線*：遠端複寫同步功能現已啟用。開始同步程序並等待資料。
* *重新配置RRRRrsynet**：正在為配對的叢集建立Volume中繼資料的單一helix複本。
* *重新傳送LocalSync*：正在為配對的叢集建立Volume中繼資料的雙螺旋複本。
* *重新擷取DataTransfer*：資料傳輸已恢復。
* * Active*：磁碟區已配對、資料正從來源傳送至目標磁碟區、資料會同步。
* *閒置*：未發生任何複寫活動。


*此程序由目標Volume驅動、可能不會顯示在來源Volume上。



=== Volume配對警告

在外掛程式擴充點的「保護」索引標籤的「Volume Pairs」（磁碟區配對）頁面上配對磁碟區之後、您可以檢視警告訊息。這些訊息會顯示在Volume Status（Volume狀態）欄中、並可顯示在配對的來源和目標端點上。

除非另有說明、否則這些訊息會顯示在配對的來源和目標端點上。

* *暫停ClusterFull*：由於目標叢集已滿、因此無法繼續進行來源複寫和大量資料傳輸。訊息僅會顯示在配對的來源端點。
* * PausedexeeedMaxSnapshotCount*：目標磁碟區已有最大快照數量、無法複寫其他快照。
* *暫停手冊*：本機磁碟區已手動暫停。必須先取消暫停、才能繼續複寫。
* *暫停ManualRemoted*：遠端Volume處於手動暫停模式。需要手動介入、才能在複寫恢復之前取消暫停遠端磁碟區。
* *暫停設定錯誤*：等待作用中的來源和目標。需要手動介入才能恢復複寫。
* *暫停QoS*：目標QoS無法維持傳入IO。複寫會自動恢復。訊息僅會顯示在配對的來源端點。
* *暫停SlowLink*：偵測到慢速連結並停止複寫。複寫會自動恢復。訊息僅會顯示在配對的來源端點。
* *暫停Volume SizeMism*：目標Volume小於來源Volume。
* * PausedXCopy*：正在向來源Volume發出SCSI XCOPY命令。必須先完成命令、才能繼續複寫。訊息僅會顯示在配對的來源端點。
* *停止設定錯誤*：偵測到永久組態錯誤。遠端Volume已清除或取消配對。不可能採取修正行動；必須建立新的配對。


[discrete]
== 如需詳細資訊、請參閱

* https://docs.netapp.com/us-en/hci/index.html["資訊文件NetApp HCI"^]
* https://www.netapp.com/data-storage/solidfire/documentation["「元件與元素資源」頁面SolidFire"^]

