---
sidebar: sidebar 
permalink: vcp_task_reports_overview.html 
summary: 使用適用於VMware vCenter Server的NNetApp Element外掛程式的「報告」頁面、檢視叢集元件和效能的相關資訊。 
keywords: netapp, hci, vcp, vcenter, element, monitor, report 
---
= 在「總覽」頁面上監控整體叢集健全狀況
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以從NetApp Element VMware vCenter Server的「VMware vCenter Server的VMware vCenter Plug-in」的「報告」延伸點之「報告」索引標籤的「總覽」頁面、檢視所選叢集的高層叢集資訊、包括整體容量、效率和效能NetApp Element 。

.步驟
. 從vCenter外掛程式選取* NetApp Element 《Management》*。
. 選擇*報告*。
. 監控「總覽」頁面上的資料。




== 報告總覽頁面資料

下列資料會出現在「報告總覽」頁面上：

* *叢集容量*：區塊儲存、中繼資料及已配置空間的剩餘容量。將指標移到進度列上以查看臨界值資訊。
* *叢集資訊*：叢集特有的資訊、例如叢集名稱、NetApp Element 叢集上執行的更新版本、MVIP和SVIP位址、以及叢集上的節點數、4K IOPS、磁碟區和工作階段。
+
** *叢集名稱*：叢集名稱。
** *儲存IP（SVIP）*：儲存虛擬IP位址（SVIP）。
** *管理IP（MVIP）*：管理虛擬IP位址（MVIP）。
** * SVIP VLAN Tag*：主要SVIP位址的VLAN識別碼。
** * MVIP VLAN Tag*：主要MVIP位址的VLAN識別碼。
** *節點數*：叢集中的作用中節點數。
** *叢集4K IOPS *：叢集一秒內可讀取/寫入的4096（4K）區塊數。
** * Element OS Version *：NetApp Element 叢集所執行的支援功能軟體版本。
** * Volume Count*：叢集上除虛擬磁碟區之外的磁碟區總數。
** *虛擬Volume Count*：叢集上的虛擬磁碟區總數。
** * iSCSI工作階段*：連接至叢集的iSCSI工作階段。
** *光纖通道工作階段*：連接至叢集的光纖通道工作階段。


* *叢集效率*：使用的整體系統容量、會考量精簡配置、重複資料刪除及壓縮等因素。在叢集上達成的計算效益、是透過比較傳統儲存設備上沒有精簡配置、重複資料刪除和壓縮的容量使用率來計算得出。
* *保護網域*：叢集的保護網域監控摘要。
+

NOTE: 保護網域功能與雙節點叢集不相容。

+
** *保護網域監控層級*：使用者選取的保護網域恢復層級。可能的值包括「機箱」或「節點」。綠色表示叢集能夠達到所選的監控層級。紅色表示叢集不再能夠達到所選的監控層級、因此需要採取修正行動。
** *剩餘區塊容量*：指出保留所選恢復層級的區塊容量百分比。
** *中繼資料容量*：指出是否有足夠的中繼資料容量可從故障中恢復、同時維持不中斷的資料可用度。正常（綠色）表示叢集有足夠的中繼資料來維持所選的監控層級。完整（紅色）表示叢集不再能夠達到所選的監控層級、因此需要採取修正行動。


* *已配置的IOPS *：叢集上磁碟區IOPS可能過度配置的摘要。已配置的IOPS計算是由叢集上所有磁碟區的總IOPS、最大IOPS和尖峰IOPS、除以叢集的最大IOPS額定值的總和所決定。
+

NOTE: 例如、如果叢集中有四個磁碟區、每個磁碟區的IOPS下限為500、IOPS上限為15、000、而IOPS尖峰次數則為15、000、IOPS下限總計為2、000、IOPS上限為6、000、而總尖峰IOPS則為6、000。如果叢集的IOPS上限為50、000、則計算結果如下：*最小IOPS *：2000、50000 = 0.04x *最大IOPS *：60000/50000 = 1.20x *爆發IOPS *：60000/50000 = 1.20x 1.00x是資源配置IOPS等於叢集之額定IOPS的基準線。

* *叢集健全狀況*：叢集健全狀況的硬體、容量和安全性元件。色碼代表下列項目：
+
** *綠色*：健康
** *黃色*：重大
** *紅色*：錯誤


* *叢集輸入/輸出*：叢集上目前執行的I/O。這些值是根據先前的I/O測量值、根據目前的I/O測量值來計算。這些是圖表中顯示的測量值：
+
** *總計*：系統中發生的合併讀寫IOPS。
** *讀取*：發生的讀取IOPS數。
** *寫入*：寫入IOPS的數量。


* *叢集處理量*：叢集上讀取、寫入及總頻寬的頻寬活動：
+
** *總計*：叢集中用於讀取和寫入活動的總MB/s。
** *讀取*：叢集的讀取活動（以MB/s為單位）。
** *寫入*：叢集的寫入活動（以MB/s為單位）。


* *效能使用率*：叢集IOPS使用率的百分比。例如、以100K IOPS執行的250K IOPS叢集、會顯示40%的使用量。




== 如需詳細資訊、請參閱

* https://docs.netapp.com/us-en/hci/index.html["資訊文件NetApp HCI"^]
* https://www.netapp.com/data-storage/solidfire/documentation["「元件與元素資源」頁面SolidFire"^]

