---
sidebar: sidebar 
permalink: vcp_task_add_manage_nodes.html 
summary: 您可以使用外掛程式在叢集組態中建立及管理節點。 
keywords: netapp, nodes, create, manage, delete, view vcp, vcenter, element 
---
= 新增及管理節點
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用外掛程式來新增 https://docs.netapp.com/us-en/hci/docs/concept_hci_nodes.html#storage-nodes["儲存節點"] 當建立叢集或需要更多儲存設備時。您也可以新增執行Element軟體的儲存節點。您必須在NetApp HCI vSphere的外掛程式之外新增不必要的運算節點。

* <<新增節點至叢集>>
* <<檢視節點詳細資料>>
* <<重新啟動節點>>
* <<關閉節點>>
* <<從叢集移除節點>>




== 新增節點至叢集

您可以使用vCenter外掛程式將儲存節點新增至叢集。

.您需要的產品
* 您要新增的節點已設定、開啟和設定。
* 叢集中每個節點上的軟體主要或次要版本號碼必須相符、軟體才能相容。例如、Element 9.0與9.1版不相容。



NOTE: 如果您要新增的節點的NetApp Element 版本與叢集上執行的版本不同、則叢集會非同步地將節點更新為NetApp Element 叢集主機上執行的版本的更新。節點更新後、會自動將自己新增至叢集。在此非同步程序期間、節點將處於「pendingActive」狀態。

.關於這項工作
節點第一次開機時、需要初始組態。當節點已設定及設定後、它會在設定節點時識別的叢集上自行登錄、並顯示在外掛程式擴充點的「*叢集>節點*」頁面的擱置節點清單中。

您可以將容量較小或較大的節點新增至現有叢集。

新增FC節點或執行NetApp Element 本軟件的儲存節點的程序相同。

.步驟
. 在vSphere Web Client中、開啟*叢集*索引標籤：
+
** 從Element vCenter外掛程式5.0開始、選取* NetApp Element 《遠端外掛程式》>「管理」>「叢集*」。
** 對於Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《支援管理》>「叢集*」。


+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。

. 按一下「*節點*」子索引標籤。
. 從下拉式清單中選取*「Pending」（擱置）*、即可檢視節點清單。
. 若要新增一或多個節點、請執行下列步驟：
+
.. 選取您要新增之每個節點的核取方塊。
.. 按一下*新增節點*。


. 檢閱您要新增的節點詳細資料、然後確認該動作。
+
當動作完成時、節點會出現在叢集的作用中節點清單中。





== 檢視節點詳細資料

您可以從外掛程式擴充點、在叢集索引標籤的節點頁面上、檢視叢集中的節點清單。您必須選取「作用中」檢視、才能查看作用中節點的清單。您可以選取以變更檢視 `Pending`、 `PendingActive`和 `All` 使用下拉式篩選器的選項。

.步驟
. 在vSphere Web Client中、開啟*叢集*索引標籤：
+
** 從Element vCenter外掛程式5.0開始、選取* NetApp Element 《遠端外掛程式》>「管理」>「叢集*」。
** 對於Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《支援管理》>「叢集*」。


+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。

. 選取「*節點*」子索引標籤。
. 選擇* Active*檢視。
. 檢視儲存叢集中節點的詳細資料。
+
您可以檢視節點ID、每個節點的名稱和狀態、已設定的IOPS、節點類型、每個節點中作用中磁碟機的數量、以及每個節點的網路資訊等資訊。





== 重新啟動節點

您可以使用外掛程式擴充點、重新啟動叢集中的一或多個作用中節點。

.您需要的產品
如果您要同時重新啟動多個節點、您已停止I/O並中斷所有iSCSI工作階段的連線。

.關於這項工作
若要重新啟動叢集、您可以選取所有叢集節點並執行重新啟動。


IMPORTANT: 此方法會重新啟動節點上的所有網路服務、導致網路連線暫時中斷。

.步驟
. 在vSphere Web Client中、開啟*叢集*索引標籤：
+
** 從Element vCenter外掛程式5.0開始、選取* NetApp Element 《遠端外掛程式》>「管理」>「叢集*」。
** 對於Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《支援管理》>「叢集*」。


+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。

. 選取「*節點*」子索引標籤。
+
.. 從* Active*檢視中、選取您要重新啟動之每個節點的核取方塊。
.. 按一下「*動作*」。
.. 選擇*重新啟動*。


. 確認行動。




== 關閉節點

您可以使用外掛程式擴充點來關閉叢集中的一或多個作用中節點。若要關閉叢集、您可以選取所有叢集節點、並執行同步關機。

.您需要的產品
如果您要同時重新啟動多個節點、您已停止I/O並中斷所有iSCSI工作階段的連線。

.步驟
. 在vSphere Web Client中、開啟*叢集*索引標籤：
+
** 從Element vCenter外掛程式5.0開始、選取* NetApp Element 《遠端外掛程式》>「管理」>「叢集*」。
** 對於Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《支援管理》>「叢集*」。


+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。

. 選取「*節點*」子索引標籤。
+
.. 從* Active*檢視中、選取您要關閉之每個節點的核取方塊。
.. 按一下「*動作*」。
.. 選擇*關機*。


. 確認行動。



NOTE: 如果在任何關機情況下、節點停機時間超過5.5分鐘、NetApp Element 則由本軟件判斷該節點不會回來加入叢集。雙Helix資料保護功能開始將單一複寫區塊寫入另一個節點、以複寫資料。視節點關機的時間長度而定、節點重新上線後、可能需要將其磁碟機新增回叢集。



== 從叢集移除節點

您可以在不再需要儲存設備或需要維護時、從叢集移除節點、而不中斷服務。

.您需要的產品
您已從叢集中移除節點中的所有磁碟機。您必須等到「移除磁碟機」程序完成、而且所有資料都已從節點移除、才能移除節點。

.關於這項工作
在一個叢集中、FC連線至少需要兩個FC節點NetApp Element 。如果只連接一個FC節點、系統會在事件記錄中觸發警示、直到您將另一個FC節點新增至叢集為止、即使所有FC網路流量只能在一個FC節點上繼續運作。

.步驟
. 在vSphere Web Client中、開啟*叢集*索引標籤：
+
** 從Element vCenter外掛程式5.0開始、選取* NetApp Element 《遠端外掛程式》>「管理」>「叢集*」。
** 對於Element vCenter外掛程式4.10及更早版本、請選取* NetApp Element 《支援管理》>「叢集*」。


+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。

. 選取「*節點*」子索引標籤。
. 若要移除一或多個節點、請執行下列步驟：
+
.. 從* Active*檢視中、選取您要移除之每個節點的核取方塊。
.. 按一下「*動作*」。
.. 選擇*移除*。


. 確認行動。
+
從叢集移除的任何節點都會顯示在「Pending」（擱置）節點清單中。





== 如需詳細資訊、請參閱

* https://docs.netapp.com/us-en/hci/index.html["資訊文件NetApp HCI"^]
* https://www.netapp.com/data-storage/solidfire/documentation["「元件與元素資源」頁面SolidFire"^]

