---
sidebar: sidebar 
permalink: vcp_task_datastores_manage.html 
summary: 您可以使用外掛程式新增在元素磁碟區上建立的管理資料存放區。 
keywords: netapp, datastore, vcp, vcenter, element 
---
= 管理資料存放區
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
使用NetApp Element VMware vCenter Server的VMware vCenter外掛程式、您可以管理以Element Volume為後盾的資料存放區。您可以建立、擴充、複製、共用或刪除資料存放區。您也可以使用VAAI取消對應、讓叢集從資源配置不足的VMFS資料存放區回收可用的區塊空間。

.您需要的是 #8217 ；需要的是什麼
* 若要建立及管理資料存放區、您必須先建立至少一個使用者帳戶。
* 若要將QoSSIOC服務搭配資料存放區使用、您必須先使用 link:vcp_task_getstarted.html#configure-qossioc-settings-using-the-plug-in["設定設定"] 在「QoSSIOC設定」頁面上、從NetApp Element 「功能性組態」延伸點取得。
* 由於資料存放區是使用所選ESXi主機所支援的最高VMFS版本所建立、因此所有叢集成員都應該執行相同版本的vSphere和ESXi、以避免VMFS相容性問題。


.選項
*  a datastore
*  the datastore list
*  a datastore
*  a datastore
*  a datastore
*  VAAI UNMAP
*  a datastore



TIP: 使用vSphere中的工作監控功能、監控資料存放區作業是否完成。



== 建立資料存放區

您可以從NetApp Element 「不受資料管理」擴充功能建立資料存放區。

.您需要的是 #8217 ；需要的是什麼
* 至少必須將一部主機連線至vCenter Server。
* 至少必須新增並執行一個叢集。
+

NOTE: 如果您使用vCenter連結模式、請確定已使用正確的vCenter Server新增叢集。

* 必須至少建立一個使用者帳戶。
* 若要將QoSSIOC服務搭配資料存放區使用、您必須先使用 link:vcp_task_getstarted.html#configure-qossioc-settings-using-the-plug-in["設定設定"] 在「QoSSIOC設定」頁面上、從NetApp Element 「功能性組態」延伸點取得。


.步驟
. 選擇* NetApp Element 《Management》（*《管理*》）>*《Management》（管理*）
+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。

. 從「Datastore（資料存放區）」頁面選取*「Create Datastor*（建立資料存放
. 輸入資料存放區的名稱。
+

TIP: 為資料中心中的每個資料存放區使用唯一名稱。對於多個叢集或vCenter Server環境、請使用描述性命名最佳實務做法。

. 選擇*下一步*。
. 為資料存放區選取一或多個必要的主機。
+

NOTE: 您至少需要一部連線的主機、才能建立新的資料存放區。如果您的主機有多個啟動器、請選取一個啟動器或主機以選取所有啟動器。如果您使用vCenter連結模式、則只有指派叢集的vCenter Server可用主機可供選取。

. 選擇*下一步*。
. 在「*組態Volume *」窗格中、選取現有的磁碟區並繼續下一步、或為新的資料存放區建立新的磁碟區：
+

NOTE: 如果您選取現有的磁碟區來建立新的資料存放區、現有資料將會遺失。如需現有的VMFS磁碟區、請參閱相關的VMware文件 https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EEFEB765-A41F-4B6D-917C-BB9ABB80FC80.html["掛載VMFS資料存放區複本"^] 和 https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.storage.doc/GUID-EBAB0D5A-3C77-4A9B-9884-3D4AD69E28DC.html["管理重複的VMFS資料存放區"^]。

+
.. 輸入備份資料存放區的磁碟區名稱。
.. 從帳戶清單中選取使用者帳戶。
.. 輸入您要建立的磁碟區總大小。
+

NOTE: 預設的Volume大小選項為GB。您可以使用以GB或GiB測量的大小來建立磁碟區：1GB = 1000 000 000位元組1GiB = 1 073 741 824位元組

+
根據預設、所有新磁碟區的512位元組模擬設定為「開啟」。

.. 在*服務品質*區域中、執行下列其中一項：
+
... 在* Policy*下、選取現有的QoS原則。
... 在*自訂設定*下、設定IOPS的自訂最小、最大和尖峰值、或使用預設的QoS值。
+

TIP: QoS原則最適合服務環境、例如資料庫、應用程式或基礎架構伺服器、很少重新開機、而且需要持續等量存取儲存設備。自訂QoSSIOC自動化最適合輕度使用的VM、例如虛擬桌面或專用的kios-type VM、這些VM可能每天重新開機、開機或關機數次。QoSSIOC自動化和QoS原則不應一起使用。

+

TIP: 如果磁碟區的IOPS值大於20、000 IOPS、則可能需要高佇列深度或多個工作階段、才能在單一磁碟區上達到此IOPS等級。





. 選擇*下一步*。
. 選擇下列其中一項來設定主機存取的授權類型：
+
** *使用Volume Access Group*：選取以明確限制哪些啟動器可以看到Volume。
** *使用CHAP*：選擇以安全的機密型存取、不限制啟動器。


. 選擇*下一步*。
. 如果您選取*使用Volume Access Group*、請為選取的主機設定Volume存取群組。
+
所選的啟動器**所需的Volume存取群組已與您在先前步驟中選取的一或多個主機啟動器相關聯

+
.. 選取其他Volume存取群組或建立新的磁碟區存取群組、以與可用的啟動器建立關聯：
+
*** *可用*：叢集中的其他Volume存取群組選項。
*** *建立新的存取群組*：輸入新存取群組的名稱、然後選取*新增*。


.. 選擇*下一步*。
.. 在「*設定主機的存取*」窗格中、將可用的主機啟動器（IQN或WWPN）與您在上一個窗格中選取的Volume存取群組建立關聯。如果主機啟動器已與磁碟區存取群組相關聯、則該啟動器的欄位為唯讀。如果主機啟動器沒有磁碟區存取群組關聯、請從啟動器旁的清單中選取選項。
.. 選擇*下一步*。


. 如果您要啟用QoSSIOC自動化、請勾選*啟用QoS和SIOC*、然後設定QoSSIOC設定。
+

TIP: 如果您使用的是QoS原則、請勿啟用QoSSIOC。QoSSIOC會覆寫及調整Volume QoS設定的QoS值。

+
如果QoSSIOC服務無法使用、請先使用 link:vcp_task_getstarted.html#configure-qossioc-settings-using-the-plug-in["設定QoSSIOC設定"]。

+
.. 選擇*啟用QoS與SIOC*。
.. 設定*爆發係數*。
+

NOTE: 突發係數是VMDK IOPS限制（SIOC）設定的倍數。如果您變更預設值、請務必使用脈衝係數值、當任何VMDK的「連拍係數」值乘以IOPS限制時、該值不會超過元素Volume的「最大連拍」限制。

.. （可選）選擇*覆蓋缺省QoS*並配置設置。
+

NOTE: 如果資料存放區的「置換預設QoS」設定已停用、則會根據每個VM的預設SIOC設定、自動設定「共用」和「限制IOPS」值。

+

TIP: 若未自訂SIOC IOPS限制、請勿自訂SIOC共用限制。

+

TIP: 根據預設、SIOC磁碟共用的上限設為「無限」。在VDI等大型VM環境中、這可能會導致叢集上的IOPS過高。啟用QoSSIOC時、請務必勾選「置換預設QoS」、並將「限制IOPS」選項設為合理的選項。



. 選擇*下一步*。
. 確認選擇並單擊*完成*。
. 若要檢視工作進度、請使用vSphere中的「工作監控」。如果資料存放區未出現在清單中、請重新整理檢視。




== 檢視資料存放區清單

您可以從NetApp Element 「資料存放區」頁面的「畫面管理」擴充點檢視可用的資料存放區。

. 選擇* NetApp Element 《Management》（資料管理）>「Management」（管理）*
+

NOTE: 如果新增兩個以上的叢集、請在導覽列中選取您要使用的叢集。

. 檢閱資料存放區清單。
+

NOTE: 不會列出橫跨多個磁碟區（混合資料存放區）的資料存放區。資料存放區檢視僅顯示所選NetApp Element 叢集ESXi主機上可用的資料存放區。

. 檢閱下列資訊：
+
** *名稱*：指派給資料存放區的名稱。
** *主機名稱*：每個相關主機裝置的位址。
** *狀態*：可能的值「可存取」或「無法存取」表示資料存放區目前是否已連線至vSphere。
** *類型*：VMware檔案系統資料存放區類型。
** * Volume Name*：指派給相關磁碟區的名稱。
** * Volume NAA*：相關磁碟區的全域唯一SCSI裝置識別碼、採用NAA IEEE登錄的延伸格式。
** *總容量（GB）*：資料存放區的總格式化容量。
** *可用容量（GB）*：資料存放區可用的空間。
** * QoSSIOC Automation *：指出是否啟用QoSSIOC自動化。可能值：
+
*** 「已啟用」：啟用QoSSIOC。
*** 「禁用」：未啟用QoSSIOC。
*** 「已超過上限」：Volume Max QoS已超過指定的限制值。








== 擴充資料存放區

您可以使用NetApp Element 「無法管理」擴充點來擴充資料存放區、以增加磁碟區大小。延伸資料存放區也會延伸與該資料存放區相關的VMFS磁區。

. 選擇* NetApp Element 《Management》（資料管理）>「Management」（管理）*
+

NOTE: 如果新增兩個以上的叢集、請在導覽列中選取您要使用的叢集。

. 在「資料存放區」頁面中、選取您要延伸的資料存放區核取方塊。
. 選取*「動作*」。
. 在產生的功能表中、選取* extend*。
. 在New Datastore Size（新資料存放區大小）欄位中、輸入新資料存放區所需的大小、然後選取GB或GiB。
+

NOTE: 擴充資料存放區會佔用整個磁碟區的大小。新的資料存放區大小不得超過所選叢集上可用的未配置空間、或叢集允許的最大磁碟區大小。

. 選擇*確定*。
. 重新整理頁面。




== 複製資料存放區

您可以使用外掛程式來複製資料存放區、包括將新的資料存放區安裝到所需的ESXi伺服器或叢集。您可以命名資料存放區複本、並設定其QoSSIOC、Volume、主機和授權類型設定。

如果來源資料存放區上有虛擬機器、則會以新名稱將複製資料存放區上的虛擬機器帶入庫存。

實體複本資料存放區的Volume大小、會與來源資料存放區的磁碟區大小相符。根據預設、所有新磁碟區的512位元組模擬設定為「開啟」。

.您需要的是 #8217 ；需要的是什麼
* 至少必須將一部主機連線至vCenter Server。
* 至少必須新增並執行一個叢集。
+

NOTE: 如果您使用vCenter連結模式、請確定已使用正確的vCenter Server新增叢集。

* 可用的未配置空間必須等於或大於來源Volume大小。
* 必須至少建立一個使用者帳戶。


.步驟
. 選擇* NetApp Element 《Management》（資料管理）>「Management」（管理）*
+

NOTE: 如果新增兩個以上的叢集、請在導覽列中選取您要使用的叢集。

. 從「*資料存放區*」頁面中、選取您要複製之資料存放區的核取方塊。
. 選取*「動作*」。
. 在產生的功能表中、選取* Clone（複製）*。
+

NOTE: 如果您嘗試複製的資料存放區包含未位於所選資料存放區上附加磁碟的虛擬機器、則不會將複製資料存放區上的虛擬機器複本新增至虛擬機器詳細目錄。

. 輸入資料存放區名稱。
+

TIP: 為資料中心中的每個資料存放區使用唯一名稱。對於多個叢集或vCenter Server環境、請使用描述性命名最佳實務做法。

. 選擇*下一步*。
. 為資料存放區選取一或多個必要的主機。
+

NOTE: 您至少需要一部連線的主機、才能建立新的資料存放區。如果您的主機有多個啟動器、請選取一個啟動器或主機以選取所有啟動器。如果您使用vCenter連結模式、則只有指派叢集的vCenter Server可用主機可供選取。

. 選擇*下一步*。
. 在「*組態Volume *」窗格中、執行下列動作：
+
.. 輸入NetApp Element 用來備份複製資料存放區的新版實體磁碟區名稱。
.. 從帳戶清單中選取使用者帳戶。
+

NOTE: 您至少需要一個現有的使用者帳戶、才能建立Volume。

.. 在*服務品質*區域中、執行下列其中一項：
+
*** 在* Policy*下、選取現有的QoS原則（若有）。
*** 在*自訂設定*下、設定IOPS的自訂最小、最大和尖峰值、或使用預設的QoS值。
+

TIP: QoS原則最適合服務環境、例如資料庫、應用程式或基礎架構伺服器、很少重新開機、而且需要持續等量存取儲存設備。自訂QoSSIOC自動化最適合輕度使用的VM、例如虛擬桌面或專用的kios-type VM、這些VM可能每天重新開機、開機或關機數次。QoSSIOC自動化和QoS原則不應一起使用。

+

TIP: 如果磁碟區的IOPS值大於20、000 IOPS、則可能需要高佇列深度或多個工作階段、才能在單一磁碟區上達到此IOPS等級。





. 選擇*下一步*。
. 選取下列其中一個選項來設定主機存取的授權類型：
+
** *使用Volume Access Group*：選取以明確限制哪些啟動器可以看到Volume。
** *使用CHAP*：選擇以安全的機密型存取、不限制啟動器。


. 選擇*下一步*。
. 如果您選取*使用Volume Access Group*、請為選取的主機設定Volume存取群組。
+
所選的啟動器**所需的Volume存取群組已與您在先前步驟中選取的一或多個主機啟動器相關聯。

+
.. 選取其他Volume存取群組或建立新的磁碟區存取群組、以與可用的啟動器建立關聯：
+
*** *可用*：叢集中的其他Volume存取群組選項。
*** *建立新的存取群組*：輸入新存取群組的名稱、然後按一下*「新增*」。


.. 選擇*下一步*。
.. 在「*設定主機的存取*」窗格中、將可用的主機啟動器（IQN或WWPN）與您在上一個窗格中選取的Volume存取群組建立關聯。
+
如果主機啟動器已與磁碟區存取群組相關聯、則該啟動器的欄位為唯讀。如果主機啟動器沒有磁碟區存取群組關聯、請從啟動器旁的下拉式清單中選取選項。

.. 選擇*下一步*。


. 如果您要啟用QoSSIOC自動化、請勾選*啟用QoS與SIOC*方塊、然後設定QoSSIOC設定。
+

IMPORTANT: 如果您使用的是QoS原則、請勿啟用QoSSIOC。QoSSIOC會覆寫及調整Volume QoS設定的QoS值。

+
如果QoSSIOC服務無法使用、您必須先從NetApp Element 「還原組態」擴充點、在「QoSSIOC設定」頁面上設定設定。

+
.. 選擇*啟用QoS與SIOC*。
.. 設定*爆發係數*。
+

NOTE: 突發係數是VMDK IOPS限制（SIOC）設定的倍數。如果您變更預設值、請務必使用脈NetApp Element 衝係數值乘以任何VMDK的IOPS上限、該值不會超過更新係數的上限。

.. *選用*：選取*置換預設QoS*並設定設定。
+
如果資料存放區的「置換預設QoS」設定已停用、則會根據每個VM的預設SIOC設定、自動設定「共用」和「限制IOPS」值。

+

TIP: 若未自訂SIOC IOPS限制、請勿自訂SIOC共用限制。

+

TIP: 根據預設、SIOC磁碟共用的上限設為「無限」。在VDI等大型VM環境中、這可能會導致叢集上的IOPS過高。啟用QoSSIOC時、請務必勾選「置換預設QoS」、並將「限制IOPS」選項設為合理的選項。



. 選擇*下一步*。
. 確認選擇並選擇*完成*。
. 重新整理頁面。




== 共用資料存放區

您可以使用NetApp Element 「無法辨識」擴充點、與一或多個主機共用資料存放區。

資料存放區只能在同一個資料中心內的主機之間共用。

.您需要的是 #8217 ；需要的是什麼
* 至少必須新增並執行一個叢集。
+

NOTE: 如果您使用vCenter連結模式、請確定已使用正確的vCenter Server新增叢集。

* 所選資料中心下必須有多部主機。


.步驟
. 選擇* NetApp Element 《Management》（資料管理）>「Management」（管理）*
+

NOTE: 如果新增兩個以上的叢集、請在導覽列中選取您要使用的叢集。

. 從*資料存放區*頁面、選取您要共用的資料存放區核取方塊。
. 選取*「動作*」。
. 在產生的功能表中、選取*分享*。
. 選取下列其中一個選項來設定主機存取的授權類型：
+
** *使用Volume Access Group*：選取此選項可明確限制哪些啟動器可以看到Volume。
** *使用CHAP*：選取此選項即可安全地以機密為基礎進行存取、而不會限制啟動器。


. 選擇*下一步*。
. 為資料存放區選取一或多個必要的主機。
+

NOTE: 您至少需要一部連線的主機、才能建立新的資料存放區。如果您的主機有多個啟動器、請選取主機來選取啟動器或所有啟動器。如果您使用vCenter連結模式、則只有指派叢集的vCenter Server可用主機可供選取。

. 選擇*下一步*。
. 如果您選取使用* Volume存取群組*、請為選取的主機設定Volume存取群組。
+
所選的啟動器**所需的Volume存取群組已與您在先前步驟中選取的一或多個主機啟動器相關聯。

+
.. 選取其他Volume存取群組或建立新的磁碟區存取群組、以與可用的啟動器建立關聯：
+
*** *可用*：叢集中的其他Volume存取群組選項。
*** *建立新的存取群組*：輸入新存取群組的名稱、然後按一下*「新增*」。


.. 選擇*下一步*。
.. 在「*設定主機的存取*」窗格中、將可用的主機啟動器（IQN或WWPN）與您在上一個窗格中選取的Volume存取群組建立關聯。
+
如果主機啟動器已與磁碟區存取群組相關聯、則該啟動器的欄位為唯讀。如果主機啟動器沒有磁碟區存取群組關聯、請從啟動器旁的下拉式清單中選取選項。



. 確認選擇並選擇*完成*。
. 重新整理頁面。




== 執行VAAI取消對應

如果您希望叢集從精簡配置的VMFS5資料存放區回收可用的區塊空間、請使用VAAI取消對應功能。

.您需要的是 #8217 ；需要的是什麼
* 確認您用於工作的資料存放區是VMFS5或更早版本。VMFS6無法使用VAAI UNMAP、因為ESXi會自動執行工作
* 確認ESXi主機系統設定已啟用VAAI UNMAP：
+
「esxcli系統設定進階清單-o/vmS3 /啟用BlockDelete」

+
整數值必須設為1才能啟用。

* 如果未針對VAAI取消對應啟用ESXi主機系統設定、請使用下列命令將整數值設為1：
+
「esxcli系統設定進階設定集-I 1 -o /vmas3/EnablBlockDelete」



.步驟
. 選擇* NetApp Element 《Management》（資料管理）>「Management」（管理）*
+

NOTE: 如果新增兩個以上的叢集、請在導覽列中選取您要使用的叢集。

. 從「*資料存放區*」頁面中、選取您要在其中使用VAAI UNMAP的資料存放區核取方塊。
. 在產生的功能表中、選取*「Actions」（動作）*。
. 選取* VAAI UNMAP *。
. 依名稱或IP位址選取主機。
. 輸入主機使用者名稱和密碼。
. 確認選擇並選擇*確定*。




== 刪除資料存放區

您可以使用NetApp Element 「不實管理」擴充點來刪除資料存放區。此作業會永久刪除資料存放區上與VM相關聯的所有檔案、並將其刪除。外掛程式不會刪除包含已登錄VM的資料存放區。

. 選擇* NetApp Element 《Management》（資料管理）>「Management」（管理）*
+

NOTE: 如果新增兩個以上的叢集、請在導覽列中選取您要使用的叢集。

. 從*資料存放區*頁面、選取您要刪除之資料存放區的核取方塊。
. 選取*「動作*」。
. 在產生的功能表中、選取*刪除*。
. （選用）如果您想要刪除NetApp Element 與資料存放區相關聯的Sfelf Volume、請選取「*刪除相關的Volume *」核取方塊。
+

NOTE: 您也可以選擇保留磁碟區、稍後再將其與其他資料存放區建立關聯。

. 選擇*是*。




== 如需詳細資訊、請參閱

* https://docs.netapp.com/us-en/hci/index.html["資訊文件NetApp HCI"^]
* https://www.netapp.com/data-storage/solidfire/documentation["「元件與元素資源」頁面SolidFire"^]

