---
sidebar: sidebar 
permalink: vcp_task_create_manage_vlans.html 
summary: 您可以使用外掛程式在叢集組態中建立及管理虛擬網路。 
keywords: netapp, VLANs, create, manage, delete, view vcp, vcenter, element 
---
= 建立及管理虛擬網路
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以將新的虛擬網路新增至叢集組態、以啟用多租戶環境連線至執行NetApp Element VMware軟體的叢集、並使用vCenter外掛程式來管理虛擬網路。

* <<Create a virtual network>>
* <<View virtual network details>>
* <<Edit a virtual network>>
* <<Delete a virtual network>>




== 建立虛擬網路

您可以將新的虛擬網路新增至叢集組態。

.您需要的是 #8217 ；需要的是什麼
* ESXi主機只有一個iSCSI軟體介面卡。
* 主機或交換器已設定用於VLAN。
* 您已識別出要指派給叢集節點上虛擬網路的IP位址區塊。
* 您已識別出一個儲存網路IP（SVIP）位址、該位址將用作所有NetApp Element 顯示儲存流量的端點。


[IMPORTANT]
====
此組態應考慮下列條件：

* VRF只能在建立VLAN時啟用。若要切換回非VRF、您必須刪除並重新建立VLAN。
* 未啟用VRF的VLAN要求啟動器與SVIP位於同一子網路中。
* 啟用VRF的VLAN不需要啟動器與SVIP位於相同的子網路、而且支援路由。


====
新增虛擬網路時、會為每個節點建立一個介面、每個節點都需要一個虛擬網路IP位址。您在建立新虛擬網路時指定的IP位址數目、必須等於或大於叢集中的節點數。虛擬網路位址會由個別節點自行大量配置及指派給個別節點。您不需要手動指派虛擬網路位址給叢集中的節點。

.步驟
. 選擇* NetApp Element 《Management》（資料管理）>「Cluster-*」（叢
+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。

. 選取*網路*子索引標籤。
. 選取*「Create VLAN*（建立VLAN*）」。
. 在「*建立VLAN*」對話方塊中、輸入VLAN的名稱。
. 輸入一個整數值作為VLAN標記。
. 輸入儲存叢集的儲存虛擬IP（SVIP）位址。
. 視需要調整網路遮罩。
+
預設值為「255．255．255．0」。

. 選用：輸入VLAN說明。
. 選用：選取「*啟用虛擬路由和轉送*」核取方塊。
+

NOTE: 虛擬路由和轉送（VRF）可讓路由器中存在多個路由表執行個體、並可同時運作。此功能僅適用於儲存網路。

+
.. 輸入虛擬網路閘道的IP位址。


. 選取要納入VLAN的主機。
+

NOTE: 附註：如果您使用vCenter連結模式、則只有指派叢集的vCenter Server可用主機可供選取。

. 設定儲存節點的IP位址區塊、如下所示：
+

NOTE: 附註：至少必須建立一個IP位址區塊。

+
.. 按一下「*建立區塊*」。
.. 輸入IP範圍的起始位址。
.. 輸入要包含在位址區塊中的IP位址數目。
+

NOTE: IP位址總數必須符合儲存叢集中的節點數。

.. 在項目外按一下以接受這些值。


. 按一下「*確定*」以建立VLAN。




== 檢視虛擬網路詳細資料

您可以從NetApp Element 「叢集」索引標籤的「網路」頁面上、從「畫面管理」擴充點檢視VLAN的網路資訊。

.步驟
. 選擇* NetApp Element 《Management》（資料管理）>「Cluster-*」（叢
+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。

. 選取「*節點*」子索引標籤。
. 選擇* Active*檢視。
. 檢視儲存叢集中節點的詳細資料。
+
您可以檢視各種資訊、例如每個VLAN的ID和名稱、每個VLAN的相關標記、指派給每個VLAN的SVIP、以及每個VLAN所使用的IP範圍。





== 編輯虛擬網路

您可以變更VLAN屬性、例如VLAN名稱、網路遮罩和IP位址區塊大小。

無法修改VLAN的VLAN標記和SVIP。閘道屬性只能針對VRF VLAN進行修改。如果存在任何iSCSI、遠端複寫或其他網路工作階段、則修改可能會失敗。

.步驟
. 選擇* NetApp Element 《Management》（資料管理）>「Cluster-*」（叢
+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。

. 選取*網路*子索引標籤。
. 選取您要編輯之VLAN的核取方塊。
. 按一下「*動作*」。
. 在產生的功能表中、按一下*編輯*。
. 在產生的功能表中、輸入VLAN的新屬性。
. 按一下「*建立區塊*」、為虛擬網路新增不連續的IP位址區塊。
. 按一下「*確定*」。




== 刪除虛擬網路

您可以永久刪除VLAN物件及其IP區塊。指派給VLAN的位址區塊會與虛擬網路失去關聯、並可重新指派給其他虛擬網路。

.步驟
. 選擇* NetApp Element 《Management》（資料管理）>「Cluster-*」（叢
+

NOTE: 如果新增兩個或多個叢集、請確定已在導覽列中選取要用於該工作的叢集。

. 選取*網路*子索引標籤。
. 選取您要刪除之VLAN的核取方塊。
. 按一下「*動作*」。
. 在產生的功能表中、按一下*刪除*。
. 確認行動。

